/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param additionalDescription Descripción adicional
 * @param address1 Dirección del usuario
 * @param address2 Dirección del usuario
 * @param addressType Tipo de dirección
 * @param city Ciudad de la dirección
 * @param country País de la dirección
 * @param createdAt Fecha de creación de la dirección
 * @param email Correo del usuario
 * @param firstName Nombre del usuario
 * @param id Identificador de la dirección del usuario
 * @param identityDocument Documento de identidad del usuario
 * @param isBillingAddress Si la dirección es de facturación
 * @param isDefault Si la dirección es por defecto
 * @param lastName Apellido del usuario
 * @param lat Latitud de la dirección
 * @param lng Longitud de la dirección
 * @param phone Teléfono del usuario
 * @param stateCode 
 * @param stateName Estado de la dirección
 * @param updatedAt Fecha de actualización de la dirección
 * @param userId Identificador del usuario
 * @param zipcode Código postal de la dirección
 */


data class CreateAddress200Response (

    /* Descripción adicional */
    @Json(name = "additional_description")
    val additionalDescription: kotlin.String? = null,

    /* Dirección del usuario */
    @Json(name = "address1")
    val address1: kotlin.String? = null,

    /* Dirección del usuario */
    @Json(name = "address2")
    val address2: kotlin.String? = null,

    /* Tipo de dirección */
    @Json(name = "address_type")
    val addressType: kotlin.String? = null,

    /* Ciudad de la dirección */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* País de la dirección */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Fecha de creación de la dirección */
    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    /* Correo del usuario */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Nombre del usuario */
    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    /* Identificador de la dirección del usuario */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Documento de identidad del usuario */
    @Json(name = "identity_document")
    val identityDocument: kotlin.String? = null,

    /* Si la dirección es de facturación */
    @Json(name = "is_billing_address")
    val isBillingAddress: kotlin.Boolean? = null,

    /* Si la dirección es por defecto */
    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = null,

    /* Apellido del usuario */
    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    /* Latitud de la dirección */
    @Json(name = "lat")
    val lat: java.math.BigDecimal? = null,

    /* Longitud de la dirección */
    @Json(name = "lng")
    val lng: java.math.BigDecimal? = null,

    /* Teléfono del usuario */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "state_code")
    val stateCode: kotlin.String? = null,

    /* Estado de la dirección */
    @Json(name = "state_name")
    val stateName: kotlin.String? = null,

    /* Fecha de actualización de la dirección */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* Identificador del usuario */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* Código postal de la dirección */
    @Json(name = "zipcode")
    val zipcode: kotlin.String? = null

)

