/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetPaymentMethods200ResponseDataInnerSpecificFields

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param allowInstallmentsPlan Indica si se permite el plan de cuotas para este método de pago.
 * @param alternativePaymentMethodName Nombre del método de pago alternativo.
 * @param enabled Indica si el método de pago está habilitado.
 * @param inputSchema Esquema de entrada para el método de pago.
 * @param labels Etiquetas asociadas al método de pago.
 * @param methodType Tipo de método de pago.
 * @param processorName Nombre del procesador de pagos.
 * @param sort Valor de clasificación del método de pago.
 * @param specificFields 
 * @param team Equipo o plataforma asociada al método de pago.
 */


data class GetPaymentMethods200ResponseDataInner (

    /* Indica si se permite el plan de cuotas para este método de pago. */
    @Json(name = "allow_installments_plan")
    val allowInstallmentsPlan: kotlin.Boolean? = null,

    /* Nombre del método de pago alternativo. */
    @Json(name = "alternative_payment_method_name")
    val alternativePaymentMethodName: kotlin.String? = null,

    /* Indica si el método de pago está habilitado. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Esquema de entrada para el método de pago. */
    @Json(name = "input_schema")
    val inputSchema: kotlin.Any? = null,

    /* Etiquetas asociadas al método de pago. */
    @Json(name = "labels")
    val labels: kotlin.Any? = null,

    /* Tipo de método de pago. */
    @Json(name = "method_type")
    val methodType: kotlin.String? = null,

    /* Nombre del procesador de pagos. */
    @Json(name = "processor_name")
    val processorName: kotlin.String? = null,

    /* Valor de clasificación del método de pago. */
    @Json(name = "sort")
    val sort: kotlin.Int? = null,

    @Json(name = "specific_fields")
    val specificFields: GetPaymentMethods200ResponseDataInnerSpecificFields? = null,

    /* Equipo o plataforma asociada al método de pago. */
    @Json(name = "team")
    val team: kotlin.String? = null

)

