/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Campos específicos para el método de pago.
 *
 * @param financialInstitutions 
 */


data class GetPaymentMethods200ResponseDataInnerSpecificFields (

    @Json(name = "financial_institutions")
    val financialInstitutions: kotlin.collections.List<GetPaymentMethods200ResponseDataInnerSpecificFieldsFinancialInstitutionsInner>? = null

)

