/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetUserAddresses200ResponseDataInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` Objeto con las direcciones del cliente
 */


data class GetUserAddresses200Response (

    /* Objeto con las direcciones del cliente */
    @Json(name = "data")
    val `data`: kotlin.collections.List<GetUserAddresses200ResponseDataInner>? = null

)

