/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param id 
 * @param providerName 
 * @param updatedAt 
 */


data class GetUserInformation200ResponseIdentityProvidersInner (

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "deleted_at")
    val deletedAt: kotlin.Any? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "provider_name")
    val providerName: kotlin.String? = null,

    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null

)

