/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cardHolder 
 * @param cardHolderDni 
 * @param company 
 * @param deletedAt 
 * @param expirationDate 
 * @param firstSix 
 * @param id 
 * @param isValid 
 * @param lastFour 
 * @param token 
 * @param verifiedAt 
 * @param verifiedBy 
 */


data class GetUserCards200ResponseDataInner (

    @Json(name = "card_holder")
    val cardHolder: kotlin.String? = null,

    @Json(name = "card_holder_dni")
    val cardHolderDni: kotlin.String? = null,

    @Json(name = "company")
    val company: kotlin.String? = null,

    @Json(name = "deleted_at")
    val deletedAt: kotlin.String? = null,

    @Json(name = "expiration_date")
    val expirationDate: kotlin.String? = null,

    @Json(name = "first_six")
    val firstSix: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "is_valid")
    val isValid: kotlin.Boolean? = null,

    @Json(name = "last_four")
    val lastFour: kotlin.String? = null,

    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "verified_at")
    val verifiedAt: kotlin.String? = null,

    @Json(name = "verified_by")
    val verifiedBy: kotlin.String? = null

)

