/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight
import org.openapitools.client.models.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount
import org.openapitools.client.models.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param brand 
 * @param category 
 * @param color 
 * @param description 
 * @param detailsUrl 
 * @param id 
 * @param imageUrl 
 * @param isbn 
 * @param manufacturer 
 * @param name 
 * @param options 
 * @param quantity 
 * @param propertySize 
 * @param sku 
 * @param taxable 
 * @param type 
 * @param uom 
 * @param upc 
 * @param taxAmount 
 * @param totalAmount 
 * @param unitPrice 
 * @param weight 
 */


data class MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner (

    @Json(name = "brand")
    var brand: kotlin.String,

    @Json(name = "category")
    var category: kotlin.String,

    @Json(name = "color")
    var color: kotlin.String,

    @Json(name = "description")
    var description: kotlin.String,

    @Json(name = "details_url")
    var detailsUrl: kotlin.String,

    @Json(name = "id")
    var id: kotlin.String,

    @Json(name = "image_url")
    var imageUrl: kotlin.String,

    @Json(name = "isbn")
    var isbn: kotlin.String,

    @Json(name = "manufacturer")
    var manufacturer: kotlin.String,

    @Json(name = "name")
    var name: kotlin.String,

    @Json(name = "options")
    var options: kotlin.String,

    @Json(name = "quantity")
    var quantity: java.math.BigDecimal,

    @Json(name = "size")
    var propertySize: kotlin.String,

    @Json(name = "sku")
    var sku: kotlin.String,

    @Json(name = "taxable")
    var taxable: kotlin.Boolean,

    @Json(name = "type")
    var type: kotlin.String,

    @Json(name = "uom")
    var uom: kotlin.String,

    @Json(name = "upc")
    var upc: kotlin.String,

    @Json(name = "tax_amount")
    var taxAmount: MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount? = null,

    @Json(name = "total_amount")
    var totalAmount: MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount? = null,

    @Json(name = "unit_price")
    var unitPrice: MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount? = null,

    @Json(name = "weight")
    var weight: MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight? = null

)

