/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled 
 * @param methodType 
 * @param specificFields 
 */


data class MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner (

    @Json(name = "enabled")
    var enabled: kotlin.Boolean,

    @Json(name = "method_type")
    var methodType: kotlin.String,

    @Json(name = "specific_fields")
    var specificFields: kotlin.Any? = null

)

