/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code 
 * @param cost 
 * @param displayCost 
 * @param displayTaxAmount 
 * @param maxDeliveryDate 
 * @param minDeliveryDate 
 * @param name 
 * @param taxAmount 
 */


data class MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner (

    @Json(name = "code")
    var code: kotlin.String? = null,

    @Json(name = "cost")
    var cost: java.math.BigDecimal? = null,

    @Json(name = "display_cost")
    var displayCost: kotlin.String? = null,

    @Json(name = "display_tax_amount")
    var displayTaxAmount: kotlin.String? = null,

    @Json(name = "max_delivery_date")
    var maxDeliveryDate: kotlin.String? = null,

    @Json(name = "min_delivery_date")
    var minDeliveryDate: kotlin.String? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "tax_amount")
    var taxAmount: java.math.BigDecimal? = null

)

