/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isFreeShipping 
 * @param maximumCostAllowed 
 */


data class MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping (

    @Json(name = "is_free_shipping")
    var isFreeShipping: kotlin.Boolean? = null,

    @Json(name = "maximum_cost_allowed")
    var maximumCostAllowed: java.math.BigDecimal? = null

)

