/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount 
 * @param code 
 * @param description 
 * @param detailsUrl 
 * @param discountCategory 
 * @param displayAmount 
 * @param reference 
 * @param freeShipping 
 */


data class MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner (

    @Json(name = "amount")
    var amount: java.math.BigDecimal,

    @Json(name = "code")
    var code: kotlin.String,

    @Json(name = "description")
    var description: kotlin.String,

    @Json(name = "details_url")
    var detailsUrl: kotlin.String,

    @Json(name = "discount_category")
    var discountCategory: kotlin.String,

    @Json(name = "display_amount")
    var displayAmount: kotlin.String,

    @Json(name = "reference")
    var reference: kotlin.String,

    @Json(name = "free_shipping")
    var freeShipping: MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping? = null

)

