/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param order 
 * @param token 
 */


data class MerchantsExternalOrdersOrderTokenGiftCardsPost200Response (

    @Json(name = "order")
    var order: MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder? = null,

    @Json(name = "token")
    var token: kotlin.String? = null

)

