/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Un objeto de la dirección del cliente
 *
 * @param additionalDescription Referencia del cliente
 * @param address1 Dirección del cliente
 * @param address2 Dirección del cliente
 * @param addressType Tipo de dirección del cliente
 * @param city Ciudad del cliente
 * @param country Código del país del cliente en 3 caracteres basado en el código ISO 3166-1 alpha-3
 * @param createdAt Fecha de creación
 * @param email 
 * @param firstName Nombre del cliente
 * @param id Identificador de la dirección
 * @param identityDocument Número de identificación del cliente
 * @param isDefault Si la dirección es la que se usara siempre
 * @param lastName Apellido del cliente
 * @param lat Latitud de la dirección
 * @param lng Longitud de la dirección
 * @param phone Teléfono del cliente
 * @param stateName Estado de la dirección del cliente
 * @param updatedAt Fecha de modificación
 * @param userId Identificador del cliente
 * @param zipcode Código postal del cliente
 */


data class OrderToken200ResponseOrderBillingAddress (

    /* Referencia del cliente */
    @Json(name = "additional_description")
    val additionalDescription: kotlin.String? = null,

    /* Dirección del cliente */
    @Json(name = "address1")
    val address1: kotlin.String? = null,

    /* Dirección del cliente */
    @Json(name = "address2")
    val address2: kotlin.String? = null,

    /* Tipo de dirección del cliente */
    @Json(name = "address_type")
    val addressType: OrderToken200ResponseOrderBillingAddress.AddressType? = null,

    /* Ciudad del cliente */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* Código del país del cliente en 3 caracteres basado en el código ISO 3166-1 alpha-3 */
    @Json(name = "country")
    val country: OrderToken200ResponseOrderBillingAddress.Country? = null,

    /* Fecha de creación */
    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Nombre del cliente */
    @Json(name = "first_name")
    val firstName: kotlin.String? = null,

    /* Identificador de la dirección */
    @Json(name = "id")
    val id: java.math.BigDecimal? = null,

    /* Número de identificación del cliente */
    @Json(name = "identity_document")
    val identityDocument: kotlin.String? = null,

    /* Si la dirección es la que se usara siempre */
    @Json(name = "is_default")
    val isDefault: kotlin.Boolean? = false,

    /* Apellido del cliente */
    @Json(name = "last_name")
    val lastName: kotlin.String? = null,

    /* Latitud de la dirección */
    @Json(name = "lat")
    val lat: java.math.BigDecimal? = null,

    /* Longitud de la dirección */
    @Json(name = "lng")
    val lng: java.math.BigDecimal? = null,

    /* Teléfono del cliente */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    /* Estado de la dirección del cliente */
    @Json(name = "state_name")
    val stateName: kotlin.String? = null,

    /* Fecha de modificación */
    @Json(name = "updated_at")
    val updatedAt: kotlin.String? = null,

    /* Identificador del cliente */
    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    /* Código postal del cliente */
    @Json(name = "zipcode")
    val zipcode: kotlin.String? = null

) {

    /**
     * Tipo de dirección del cliente
     *
     * Values: HOME,OFFICE,OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class AddressType(val value: kotlin.String) {
        @Json(name = "home") HOME("home"),
        @Json(name = "office") OFFICE("office"),
        @Json(name = "other") OTHER("other");
    }
    /**
     * Código del país del cliente en 3 caracteres basado en el código ISO 3166-1 alpha-3
     *
     * Values: ECU,BRA,PER,COL,CHL,MEX,ARG
     */
    @JsonClass(generateAdapter = false)
    enum class Country(val value: kotlin.String) {
        @Json(name = "ECU") ECU("ECU"),
        @Json(name = "BRA") BRA("BRA"),
        @Json(name = "PER") PER("PER"),
        @Json(name = "COL") COL("COL"),
        @Json(name = "CHL") CHL("CHL"),
        @Json(name = "MEX") MEX("MEX"),
        @Json(name = "ARG") ARG("ARG");
    }
}

