/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Agregar datos que se requieran adicionales de parte del comercio en clave-valor (JSON)
 *
 * @param origin 
 * @param state 
 */


data class OrderToken200ResponseOrderMetadata (

    @Json(name = "origin")
    val origin: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null

)

