/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * El precio unitario del producto
 *
 * @param amount El precio unitario del producto. 
 * @param currency Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 
 * @param currencySymbol Simbolo de la moneda de tu comercio
 * @param displayAmount El precio unitario del producto que se mostrara en el checkout. 
 */


data class OrderToken200ResponseOrderItemsInnerUnitPrice (

    /* El precio unitario del producto.  */
    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null,

    /* Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3  */
    @Json(name = "currency")
    val currency: kotlin.String? = null,

    /* Simbolo de la moneda de tu comercio */
    @Json(name = "currency_symbol")
    val currencySymbol: kotlin.String? = null,

    /* El precio unitario del producto que se mostrara en el checkout.  */
    @Json(name = "display_amount")
    val displayAmount: kotlin.String? = null

)

