/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails
import org.openapitools.client.models.OrderToken200ResponseOrderShippingOptionsDetailsAddressCoordinates
import org.openapitools.client.models.OrderToken200ResponseOrderShippingOptionsDetailsContact

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * El detalle del método de envío 
 *
 * @param additionalDetails 
 * @param address Dirección de la tienda
 * @param addressCoordinates 
 * @param contact 
 * @param storeName Nombre de la tienda, por defecto te devolvera all
 */


data class OrderToken200ResponseOrderShippingOptionsDetails (

    @Json(name = "additional_details")
    val additionalDetails: OrderToken200ResponseOrderShippingOptionsDetailsAdditionalDetails? = null,

    /* Dirección de la tienda */
    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "address_coordinates")
    val addressCoordinates: OrderToken200ResponseOrderShippingOptionsDetailsAddressCoordinates? = null,

    @Json(name = "contact")
    val contact: OrderToken200ResponseOrderShippingOptionsDetailsContact? = null,

    /* Nombre de la tienda, por defecto te devolvera all */
    @Json(name = "store_name")
    val storeName: kotlin.String? = null

)

