/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderTokenRequestOrderDiscountsInnerFreeShipping

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount El monto total del descuento de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param code El código del descuento que se aplicara en la orden
 * @param description La descripción del descuento
 * @param detailsUrl URL del descuento
 * @param discountCategory Categoría del descuento
 * @param freeShipping 
 * @param reference Referencia del descuento
 * @param targetType Componente donde se aplicó el descuento
 * @param type Tipo del descuento aplicado
 */


data class OrderTokenRequestOrderDiscountsInner (

    /* El monto total del descuento de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    /* El código del descuento que se aplicara en la orden */
    @Json(name = "code")
    val code: kotlin.String,

    /* La descripción del descuento */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* URL del descuento */
    @Json(name = "details_url")
    val detailsUrl: kotlin.String? = null,

    /* Categoría del descuento */
    @Json(name = "discount_category")
    val discountCategory: kotlin.String? = null,

    @Json(name = "free_shipping")
    val freeShipping: OrderTokenRequestOrderDiscountsInnerFreeShipping? = null,

    /* Referencia del descuento */
    @Json(name = "reference")
    val reference: kotlin.String? = null,

    /* Componente donde se aplicó el descuento */
    @Json(name = "target_type")
    val targetType: OrderTokenRequestOrderDiscountsInner.TargetType? = null,

    /* Tipo del descuento aplicado */
    @Json(name = "type")
    val type: OrderTokenRequestOrderDiscountsInner.Type? = null

) {

    /**
     * Componente donde se aplicó el descuento
     *
     * Values: SHIPPING,ITEM
     */
    @JsonClass(generateAdapter = false)
    enum class TargetType(val value: kotlin.String) {
        @Json(name = "shipping") SHIPPING("shipping"),
        @Json(name = "item") ITEM("item");
    }
    /**
     * Tipo del descuento aplicado
     *
     * Values: FREE_SHIPPING,ORDER_VALUE,PRODUCT
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "free_shipping") FREE_SHIPPING("free_shipping"),
        @Json(name = "order_value") ORDER_VALUE("order_value"),
        @Json(name = "product") PRODUCT("product");
    }
}

