/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderTokenRequestOrderPaymentData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Objeto donde se vera el pago de la orden
 *
 * @param `data` 
 */


data class OrderTokenRequestOrderPayment (

    @Json(name = "data")
    val `data`: OrderTokenRequestOrderPaymentData? = null

)

