/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Peso del producto
 *
 * @param unit Unidad de peso del producto
 * @param weight Peso del producto
 */


data class OrderToken200ResponseOrderItemsInnerWeight (

    /* Unidad de peso del producto */
    @Json(name = "unit")
    val unit: kotlin.String? = null,

    /* Peso del producto */
    @Json(name = "weight")
    val weight: java.math.BigDecimal? = null

)

