/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Agregar datos que se requieran adicionales de parte del comercio en clave-valor (JSON)
 *
 * @param key1 
 * @param key2 
 */


data class OrderTokenRequestOrderMetadata (

    @Json(name = "key1")
    val key1: kotlin.String? = null,

    @Json(name = "key2")
    val key2: kotlin.String? = null

)

