/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contacto de la tienda
 *
 * @param name Nombre del contacto del comercio
 * @param phone Teléfono del contacto del comercio
 */


data class OrderToken200ResponseOrderShippingOptionsDetailsContact (

    /* Nombre del contacto del comercio */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Teléfono del contacto del comercio */
    @Json(name = "phone")
    val phone: kotlin.String? = null

)

