/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isFreeShipping Si el producto tiene envío gratis
 * @param maximumCostAllowed El monto maximo del descuento.
 */


data class OrderToken200ResponseOrderDiscountsInnerFreeShipping (

    /* Si el producto tiene envío gratis */
    @Json(name = "is_free_shipping")
    val isFreeShipping: kotlin.Boolean? = false,

    /* El monto maximo del descuento. */
    @Json(name = "maximum_cost_allowed")
    val maximumCostAllowed: java.math.BigDecimal? = null

)

