/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * El precio unitario del producto
 *
 * @param amount El precio unitario del producto. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param currency Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 
 * @param currencySymbol Simbolo de la moneda de tu comercio
 */


data class OrderTokenRequestOrderItemsInnerUnitPrice (

    /* El precio unitario del producto. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    /* Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3  */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* Simbolo de la moneda de tu comercio */
    @Json(name = "currency_symbol")
    val currencySymbol: OrderTokenRequestOrderItemsInnerUnitPrice.CurrencySymbol

) {

    /**
     * Simbolo de la moneda de tu comercio
     *
     * Values: DOLLAR,S_SLASH_PERIOD,R_DOLLAR
     */
    @JsonClass(generateAdapter = false)
    enum class CurrencySymbol(val value: kotlin.String) {
        @Json(name = "$") DOLLAR("$"),
        @Json(name = "S/.") S_SLASH_PERIOD("S/."),
        @Json(name = "R$") R_DOLLAR("R$");
    }
}

