/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderTokenRequestOrderShippingMethodSchedulerInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Método de envío
 *
 * @param code código método de envío
 * @param cost Costo de envío
 * @param displayCost Costo de envío que se mostrara en el checkout 
 * @param displayTaxAmount Monto de impuestos del envío que se mostrara en el checkout
 * @param maxDeliveryDate Fecha máxima de delivery
 * @param minDeliveryDate Fecha más cercana al delivery
 * @param name Nombre del método de envío
 * @param scheduler Se usa para configurar un envío programado
 * @param taxAmount Monto de impuestos del envío
 */


data class OrderTokenRequestOrderShippingMethod (

    /* código método de envío */
    @Json(name = "code")
    val code: kotlin.String? = null,

    /* Costo de envío */
    @Json(name = "cost")
    val cost: java.math.BigDecimal? = null,

    /* Costo de envío que se mostrara en el checkout  */
    @Json(name = "display_cost")
    val displayCost: kotlin.String? = null,

    /* Monto de impuestos del envío que se mostrara en el checkout */
    @Json(name = "display_tax_amount")
    val displayTaxAmount: kotlin.String? = null,

    /* Fecha máxima de delivery */
    @Json(name = "max_delivery_date")
    val maxDeliveryDate: kotlin.String? = null,

    /* Fecha más cercana al delivery */
    @Json(name = "min_delivery_date")
    val minDeliveryDate: kotlin.String? = null,

    /* Nombre del método de envío */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Se usa para configurar un envío programado */
    @Json(name = "scheduler")
    val scheduler: kotlin.collections.List<OrderTokenRequestOrderShippingMethodSchedulerInner>? = null,

    /* Monto de impuestos del envío */
    @Json(name = "tax_amount")
    val taxAmount: java.math.BigDecimal? = null

)

