/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderToken200ResponseOrderItemsInnerTaxAmount
import org.openapitools.client.models.OrderToken200ResponseOrderItemsInnerTotalAmount
import org.openapitools.client.models.OrderToken200ResponseOrderItemsInnerUnitPrice
import org.openapitools.client.models.OrderToken200ResponseOrderItemsInnerWeight

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Detalle del producto 
 *
 * @param brand Marca del producto
 * @param category Categoría del producto
 * @param color Color del producto
 * @param description Descripción del producto
 * @param detailsUrl URL del producto en la página
 * @param discounts son los descuentos aplicados al producto
 * @param id Identificador del producto del comercio
 * @param imageUrl URL donde se encuentra alojada la imagen de tu producto 
 * @param isbn Sistema internacional de numeración de libros (International Standard Book Number)
 * @param manufacturer Fabricante del producto
 * @param name Nombre del producto
 * @param options 
 * @param quantity Es la cantidad del producto que comprara el usuario
 * @param propertySize Tamaño del producto
 * @param sku Número de referencia único (Stock Keeping Unit)
 * @param taxAmount 
 * @param taxable Si es que el producto aplica algún impuesto
 * @param totalAmount 
 * @param type Tipo de producto
 * @param unitPrice 
 * @param uom Unidad de medida (Unit of Measure)
 * @param upc Código universal del producto (Universal Product Code)
 * @param weight 
 */


data class OrderToken200ResponseOrderItemsInner (

    /* Marca del producto */
    @Json(name = "brand")
    val brand: kotlin.String? = null,

    /* Categoría del producto */
    @Json(name = "category")
    val category: kotlin.String? = null,

    /* Color del producto */
    @Json(name = "color")
    val color: kotlin.String? = null,

    /* Descripción del producto */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* URL del producto en la página */
    @Json(name = "details_url")
    val detailsUrl: kotlin.String? = null,

    /* son los descuentos aplicados al producto */
    @Json(name = "discounts")
    val discounts: kotlin.collections.List<kotlin.Any>? = null,

    /* Identificador del producto del comercio */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* URL donde se encuentra alojada la imagen de tu producto  */
    @Json(name = "image_url")
    val imageUrl: kotlin.String? = null,

    /* Sistema internacional de numeración de libros (International Standard Book Number) */
    @Json(name = "isbn")
    val isbn: kotlin.String? = null,

    /* Fabricante del producto */
    @Json(name = "manufacturer")
    val manufacturer: kotlin.String? = null,

    /* Nombre del producto */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "options")
    val options: kotlin.String? = null,

    /* Es la cantidad del producto que comprara el usuario */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal? = null,

    /* Tamaño del producto */
    @Json(name = "size")
    val propertySize: kotlin.String? = null,

    /* Número de referencia único (Stock Keeping Unit) */
    @Json(name = "sku")
    val sku: kotlin.String? = null,

    @Json(name = "tax_amount")
    val taxAmount: OrderToken200ResponseOrderItemsInnerTaxAmount? = null,

    /* Si es que el producto aplica algún impuesto */
    @Json(name = "taxable")
    val taxable: kotlin.Boolean? = false,

    @Json(name = "total_amount")
    val totalAmount: OrderToken200ResponseOrderItemsInnerTotalAmount? = null,

    /* Tipo de producto */
    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "unit_price")
    val unitPrice: OrderToken200ResponseOrderItemsInnerUnitPrice? = null,

    /* Unidad de medida (Unit of Measure) */
    @Json(name = "uom")
    val uom: kotlin.String? = null,

    /* Código universal del producto (Universal Product Code) */
    @Json(name = "upc")
    val upc: kotlin.String? = null,

    @Json(name = "weight")
    val weight: OrderToken200ResponseOrderItemsInnerWeight? = null

)

