/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param onCanceled 
 * @param onFailed 
 * @param onReject 
 * @param onSuccess 
 */


data class PurchaseRequestSpecificFieldsCallbacks (

    @Json(name = "on_canceled")
    val onCanceled: kotlin.String? = null,

    @Json(name = "on_failed")
    val onFailed: kotlin.String? = null,

    @Json(name = "on_reject")
    val onReject: kotlin.String? = null,

    @Json(name = "on_success")
    val onSuccess: kotlin.String? = null

)

