/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param email 
 * @param id 
 * @param lastUpdated 
 * @param merchantId 
 * @param name 
 * @param phone 
 * @param role 
 * @param storeCode 
 */


data class RegisterMerchantUsers200ResponseData (

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "deleted_at")
    val deletedAt: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "last_updated")
    val lastUpdated: kotlin.String? = null,

    @Json(name = "merchant_id")
    val merchantId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "role")
    val role: kotlin.String? = null,

    @Json(name = "store_code")
    val storeCode: kotlin.String? = null

)

