/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param ID 
 * @param updatedAt 
 * @param accountNumber 
 * @param accountType 
 * @param amplitudeId 
 * @param apiKey 
 * @param autoApproveOrderInCore 
 * @param bankName 
 * @param businessUrl 
 * @param city 
 * @param country 
 * @param currency 
 * @param domain 
 * @param gtmId 
 * @param industry 
 * @param logo 
 * @param managedByDuna 
 * @param merchantCategoryCode 
 * @param merchantEvents 
 * @param name 
 * @param onboardingStep 
 * @param orderApiPort 
 * @param orderApiUrl 
 * @param orderPickupApiUrl 
 * @param pickupTokenUrl 
 * @param platform 
 * @param policies 
 * @param privacyPoliciesUrl 
 * @param service 
 * @param shortName 
 * @param statusChangesNotificationUrl 
 * @param storefrontBaseUrl 
 * @param storefrontPrivateUrl 
 * @param termAndConditionsUrl 
 * @param timezone 
 * @param token 
 * @param useDunaSend 
 * @param vendorId 
 */


data class GetAllMerchants200ResponseDataInner (

    @Json(name = "CreatedAt")
    var createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "DeletedAt")
    var deletedAt: kotlin.String? = null,

    @Json(name = "ID")
    var ID: kotlin.String? = null,

    @Json(name = "UpdatedAt")
    var updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "account_number")
    var accountNumber: kotlin.String? = null,

    @Json(name = "account_type")
    var accountType: kotlin.String? = null,

    @Json(name = "amplitude_id")
    var amplitudeId: kotlin.String? = null,

    @Json(name = "api_key")
    var apiKey: kotlin.String? = null,

    @Json(name = "auto_approve_order_in_core")
    var autoApproveOrderInCore: kotlin.Boolean? = null,

    @Json(name = "bank_name")
    var bankName: kotlin.String? = null,

    @Json(name = "business_url")
    var businessUrl: kotlin.String? = null,

    @Json(name = "city")
    var city: kotlin.String? = null,

    @Json(name = "country")
    var country: kotlin.String? = null,

    @Json(name = "currency")
    var currency: kotlin.String? = null,

    @Json(name = "domain")
    var domain: kotlin.String? = null,

    @Json(name = "gtm_id")
    var gtmId: kotlin.String? = null,

    @Json(name = "industry")
    var industry: kotlin.String? = null,

    @Json(name = "logo")
    var logo: kotlin.String? = null,

    @Json(name = "managed_by_duna")
    var managedByDuna: kotlin.Boolean? = null,

    @Json(name = "merchant_category_code")
    var merchantCategoryCode: kotlin.String? = null,

    @Json(name = "merchant_events")
    var merchantEvents: kotlin.collections.MutableList<kotlin.Any>? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "onboarding_step")
    var onboardingStep: kotlin.Int? = null,

    @Json(name = "order_api_port")
    var orderApiPort: kotlin.Int? = null,

    @Json(name = "order_api_url")
    var orderApiUrl: kotlin.String? = null,

    @Json(name = "order_pickup_api_url")
    var orderPickupApiUrl: kotlin.String? = null,

    @Json(name = "pickup_token_url")
    var pickupTokenUrl: kotlin.String? = null,

    @Json(name = "platform")
    var platform: kotlin.String? = null,

    @Json(name = "policies")
    var policies: kotlin.collections.MutableList<kotlin.Any>? = null,

    @Json(name = "privacy_policies_url")
    var privacyPoliciesUrl: kotlin.String? = null,

    @Json(name = "service")
    var service: kotlin.String? = null,

    @Json(name = "short_name")
    var shortName: kotlin.String? = null,

    @Json(name = "status_changes_notification_url")
    var statusChangesNotificationUrl: kotlin.String? = null,

    @Json(name = "storefront_base_url")
    var storefrontBaseUrl: kotlin.String? = null,

    @Json(name = "storefront_private_url")
    var storefrontPrivateUrl: kotlin.String? = null,

    @Json(name = "term_and_conditions_url")
    var termAndConditionsUrl: kotlin.String? = null,

    @Json(name = "timezone")
    var timezone: kotlin.String? = null,

    @Json(name = "token")
    var token: kotlin.String? = null,

    @Json(name = "use_duna_send")
    var useDunaSend: kotlin.String? = null,

    @Json(name = "vendor_id")
    var vendorId: kotlin.String? = null

)

