/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models

import io.deuna.deuna-android-sdk.models.GetMerchantsPaymentsMethods200ResponseDataInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` Lista de los métodos de pago de la tienda para esa orden
 */


data class GetMerchantsPaymentsMethods200Response (

    /* Lista de los métodos de pago de la tienda para esa orden */
    @Json(name = "data")
    var `data`: kotlin.collections.MutableList<GetMerchantsPaymentsMethods200ResponseDataInner>? = null

)

