/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ID 
 * @param createdAt 
 * @param deletedAt 
 * @param event 
 * @param merchantId 
 * @param updatedAt 
 */


data class IdentityToken200ResponseMerchantEventsInner (

    @Json(name = "ID")
    var ID: kotlin.Int? = null,

    @Json(name = "created_at")
    var createdAt: kotlin.String? = null,

    @Json(name = "deleted_at")
    var deletedAt: kotlin.String? = null,

    @Json(name = "event")
    var event: kotlin.String? = null,

    @Json(name = "merchant_id")
    var merchantId: kotlin.String? = null,

    @Json(name = "updated_at")
    var updatedAt: kotlin.String? = null

)

