/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email Email del usuario
 * @param otp Código OTP enviado al usuario
 */


data class LoginWithOtpRequest (

    /* Email del usuario */
    @Json(name = "email")
    var email: kotlin.String,

    /* Código OTP enviado al usuario */
    @Json(name = "otp")
    var otp: kotlin.String? = null

)

