/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount El monto total del descuento de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param refIdx ID de referencia del descuento que se aplicara en la orden
 */


data class OrderTokenRequestOrderItemsInnerDiscountsInner (

    /* El monto total del descuento de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "amount")
    var amount: java.math.BigDecimal,

    /* ID de referencia del descuento que se aplicara en la orden */
    @Json(name = "ref_idx")
    var refIdx: java.math.BigDecimal

)

