/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Tarifa de envío
 *
 * @param discounts 
 * @param originalAmount Precio original de envío
 * @param totalDiscount Descuento total en el envío
 */


data class OrderToken200ResponseOrderShipping (

    @Json(name = "discounts")
    var discounts: kotlin.collections.MutableList<kotlin.Any>? = null,

    /* Precio original de envío */
    @Json(name = "original_amount")
    var originalAmount: java.math.BigDecimal? = null,

    /* Descuento total en el envío */
    @Json(name = "total_discount")
    var totalDiscount: java.math.BigDecimal? = null

)

