/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email Email del cliente
 * @param id identificador del cliente 
 */


data class OrderTokenRequestOrderPaymentDataCustomer (

    /* Email del cliente */
    @Json(name = "email")
    var email: kotlin.String? = null,

    /* identificador del cliente  */
    @Json(name = "id")
    var id: kotlin.String? = null

)

