/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models

import io.deuna.deuna-android-sdk.models.OrderToken200ResponseOrder

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param order 
 * @param token Es el token de la orden generado por DEUNA, el mismo que será usado para el **Widget Checkout** 
 */


data class OrderToken200Response (

    @Json(name = "order")
    var order: OrderToken200ResponseOrder? = null,

    /* Es el token de la orden generado por DEUNA, el mismo que será usado para el **Widget Checkout**  */
    @Json(name = "token")
    var token: kotlin.String? = null

)

