/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * El precio total del producto es: la cantidad del producto multiplicado por el precio unitario más los impuestos
 *
 * @param amount El precio total de los productos. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param currency Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3
 * @param currencySymbol Simbolo de la moneda de tu comercio
 * @param originalAmount El precio original de los productos, esto representa el precio sin ningun descuento. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param totalDiscount El total de los descuentos aplicados sobre los items
 */


data class OrderTokenRequestOrderItemsInnerTotalAmount (

    /* El precio total de los productos. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "amount")
    var amount: java.math.BigDecimal? = null,

    /* Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 */
    @Json(name = "currency")
    var currency: OrderTokenRequestOrderItemsInnerTotalAmount.Currency? = null,

    /* Simbolo de la moneda de tu comercio */
    @Json(name = "currency_symbol")
    var currencySymbol: OrderTokenRequestOrderItemsInnerTotalAmount.CurrencySymbol? = null,

    /* El precio original de los productos, esto representa el precio sin ningun descuento. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "original_amount")
    var originalAmount: java.math.BigDecimal? = null,

    /* El total de los descuentos aplicados sobre los items */
    @Json(name = "total_discount")
    var totalDiscount: java.math.BigDecimal? = null

) {

    /**
     * Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3
     *
     * Values: uSD,mXN,cOP,cLP,bRL,aRS,pEN
     */
    @JsonClass(generateAdapter = false)
    enum class Currency(val value: kotlin.String) {
        @Json(name = "USD") uSD("USD"),
        @Json(name = "MXN") mXN("MXN"),
        @Json(name = "COP") cOP("COP"),
        @Json(name = "CLP") cLP("CLP"),
        @Json(name = "BRL") bRL("BRL"),
        @Json(name = "ARS") aRS("ARS"),
        @Json(name = "PEN") pEN("PEN");
    }
    /**
     * Simbolo de la moneda de tu comercio
     *
     * Values: dollar,sSlashPeriod,rDollar
     */
    @JsonClass(generateAdapter = false)
    enum class CurrencySymbol(val value: kotlin.String) {
        @Json(name = "$") dollar("$"),
        @Json(name = "S/.") sSlashPeriod("S/."),
        @Json(name = "R$") rDollar("R$");
    }
}

