/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Detalles adicionales, puede llevar campos diferentes campos como  pickup_time | stock_location
 *
 * @param addressNotes Notas para la dirección, en caso sea **delivery**
 * @param pickupTime Hora que el cliente tiene que recoger la orden, en caso sea **pickup**
 * @param stockLocation Nombre de la tienda que el cliente tiene que recoger la orden, en caso sea **pickup**
 */


data class OrderTokenRequestOrderShippingOptionsDetailsAdditionalDetails (

    /* Notas para la dirección, en caso sea **delivery** */
    @Json(name = "address_notes")
    var addressNotes: kotlin.String? = null,

    /* Hora que el cliente tiene que recoger la orden, en caso sea **pickup** */
    @Json(name = "pickup_time")
    var pickupTime: kotlin.String? = null,

    /* Nombre de la tienda que el cliente tiene que recoger la orden, en caso sea **pickup** */
    @Json(name = "stock_location")
    var stockLocation: kotlin.String? = null

)

