/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Monto del pago de la orden 
 *
 * @param amount Monto total de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos.
 * @param currency Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 
 */


data class OrderTokenRequestOrderPaymentDataAmount (

    /* Monto total de la orden. Deberá estar expresado en centavos, por ejemplo si el monto es $10.00 estará representado como 1000 lo que significa 10 dólares 0 centavos. */
    @Json(name = "amount")
    var amount: java.math.BigDecimal? = null,

    /* Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3  */
    @Json(name = "currency")
    var currency: OrderTokenRequestOrderPaymentDataAmount.Currency? = null

) {

    /**
     * Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 
     *
     * Values: uSD,mXN,cOP,cLP,bRL,aRS,pEN
     */
    @JsonClass(generateAdapter = false)
    enum class Currency(val value: kotlin.String) {
        @Json(name = "USD") uSD("USD"),
        @Json(name = "MXN") mXN("MXN"),
        @Json(name = "COP") cOP("COP"),
        @Json(name = "CLP") cLP("CLP"),
        @Json(name = "BRL") bRL("BRL"),
        @Json(name = "ARS") aRS("ARS"),
        @Json(name = "PEN") pEN("PEN");
    }
}

