/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Datos del comercio
 *
 * @param id Identificador de la tienda
 * @param storeCode código de la tienda
 */


data class OrderTokenRequestOrderPaymentDataMerchant (

    /* Identificador de la tienda */
    @Json(name = "id")
    var id: kotlin.String? = null,

    /* código de la tienda */
    @Json(name = "store_code")
    var storeCode: kotlin.String? = null

)

