/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Objeto con la informacion de la tarjeta
 *
 * @param cardBrand Procesador de la tarjeta
 * @param firstSix Primeros 6 digitos de la tarjeta
 * @param lastFour Ultimos 4 digitos de la tarjeta
 */


data class OrderTokenRequestOrderPaymentDataFromCard (

    /* Procesador de la tarjeta */
    @Json(name = "card_brand")
    var cardBrand: OrderTokenRequestOrderPaymentDataFromCard.CardBrand? = null,

    /* Primeros 6 digitos de la tarjeta */
    @Json(name = "first_six")
    var firstSix: kotlin.String? = null,

    /* Ultimos 4 digitos de la tarjeta */
    @Json(name = "last_four")
    var lastFour: kotlin.String? = null

) {

    /**
     * Procesador de la tarjeta
     *
     * Values: visa,mastercard,americanExpress,diners
     */
    @JsonClass(generateAdapter = false)
    enum class CardBrand(val value: kotlin.String) {
        @Json(name = "Visa") visa("Visa"),
        @Json(name = "Mastercard") mastercard("Mastercard"),
        @Json(name = "American Express") americanExpress("American Express"),
        @Json(name = "Diners") diners("Diners");
    }
}

