/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * El precio total del producto es: la cantidad del producto multiplicado por el precio unitario más los impuestos
 *
 * @param amount El precio total de los productos.
 * @param currency Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3
 * @param currencySymbol Simbolo de la moneda de tu comercio
 * @param displayAmount El precio total de los productos que se mostrara en el checkout.
 * @param displayOriginalAmount El precio original de los productos, esto representa el precio sin ningun descuento que se mostrara en el checkout.
 * @param displayTotalDiscount Es el descuento total del producto que se mostrara en el checkout.
 * @param originalAmount El precio original de los productos, esto representa el precio sin ningun descuento.
 * @param totalDiscount Es el descuento total del producto.
 */


data class OrderToken200ResponseOrderItemsInnerTotalAmount (

    /* El precio total de los productos. */
    @Json(name = "amount")
    var amount: java.math.BigDecimal? = null,

    /* Representa la moneda de uso del comercio en 3 caracteres bajo la ISO 3166-1 alpha-3 */
    @Json(name = "currency")
    var currency: kotlin.String? = null,

    /* Simbolo de la moneda de tu comercio */
    @Json(name = "currency_symbol")
    var currencySymbol: kotlin.String? = null,

    /* El precio total de los productos que se mostrara en el checkout. */
    @Json(name = "display_amount")
    var displayAmount: kotlin.String? = null,

    /* El precio original de los productos, esto representa el precio sin ningun descuento que se mostrara en el checkout. */
    @Json(name = "display_original_amount")
    var displayOriginalAmount: kotlin.String? = null,

    /* Es el descuento total del producto que se mostrara en el checkout. */
    @Json(name = "display_total_discount")
    var displayTotalDiscount: kotlin.String? = null,

    /* El precio original de los productos, esto representa el precio sin ningun descuento. */
    @Json(name = "original_amount")
    var originalAmount: java.math.BigDecimal? = null,

    /* Es el descuento total del producto. */
    @Json(name = "total_discount")
    var totalDiscount: java.math.BigDecimal? = null

)

