/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Permite sobrescribir configuraciones globales del cliente y verificar o no verificar la operabilidad de la tarjeta
 *
 * @param invokeCardVerification En caso de enviar False e independientemente de la configuración global del comercio, no será ejecutada la verificación. En caso de enviar True e independientemente de la configuración global del comercio, se ejecutará la verificación.
 */


data class PostUsersUserIdCardsRequestCardVerificationConfig (

    /* En caso de enviar False e independientemente de la configuración global del comercio, no será ejecutada la verificación. En caso de enviar True e independientemente de la configuración global del comercio, se ejecutará la verificación. */
    @Json(name = "invoke_card_verification")
    var invokeCardVerification: kotlin.Boolean? = null

)

