/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models

import io.deuna.deuna-android-sdk.models.PurchaseRequestSpecificFieldsCallbacks

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param callbacks 
 * @param description 
 * @param financialInstitution 
 */


data class PurchaseRequestSpecificFields (

    @Json(name = "callbacks")
    var callbacks: PurchaseRequestSpecificFieldsCallbacks? = null,

    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "financial_institution")
    var financialInstitution: kotlin.String? = null

)

