/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.deuna-android-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email Correo del usuario a registrar
 * @param firstName Nombre del usuario
 * @param lastName Apellido del usuario
 * @param phone Número de telefono del usuario
 * @param identityDocument Documento de identidad del usuario
 */


data class UsersRegisterRequest (

    /* Correo del usuario a registrar */
    @Json(name = "email")
    var email: kotlin.String,

    /* Nombre del usuario */
    @Json(name = "first_name")
    var firstName: kotlin.String,

    /* Apellido del usuario */
    @Json(name = "last_name")
    var lastName: kotlin.String,

    /* Número de telefono del usuario */
    @Json(name = "phone")
    var phone: kotlin.String,

    /* Documento de identidad del usuario */
    @Json(name = "identity_document")
    var identityDocument: kotlin.String? = null

)

