/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2002
     */
    isSandbox?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    privateKey?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    signingSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    updatedAt?: string;
}
