/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2007IdentityProviders } from './inline-response2007-identity-providers';
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    createdAt?: string;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse2007
     */
    deletedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    id?: string;
    /**
     * 
     * @type {Array<InlineResponse2007IdentityProviders>}
     * @memberof InlineResponse2007
     */
    identityProviders?: Array<InlineResponse2007IdentityProviders>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2007
     */
    isGuest?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2007
     */
    isPhoneVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    merchantId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    updatedAt?: string;
}
