/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentscardsusersuserIdcardsData } from './paymentscardsusersuser-idcards-data';
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {PaymentscardsusersuserIdcardsData}
     * @memberof InlineResponse2003
     */
    data?: PaymentscardsusersuserIdcardsData;
}
