/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersLoginBody
 */
export interface UsersLoginBody {
    /**
     * 
     * @type {string}
     * @memberof UsersLoginBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersLoginBody
     */
    otp?: string;
}
