/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse2001Data} from './model/InlineResponse2001Data';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse2004} from './model/InlineResponse2004';
import {InlineResponse2005} from './model/InlineResponse2005';
import {InlineResponse2006} from './model/InlineResponse2006';
import {InlineResponse2007} from './model/InlineResponse2007';
import {InlineResponse2007IdentityProviders} from './model/InlineResponse2007IdentityProviders';
import {InlineResponse2008} from './model/InlineResponse2008';
import {InlineResponse401} from './model/InlineResponse401';
import {InlineResponse4011} from './model/InlineResponse4011';
import {MerchantIdApplicationsBody} from './model/MerchantIdApplicationsBody';
import {PaymentscardsusersuserIdcardsData} from './model/PaymentscardsusersuserIdcardsData';
import {PaymentscardsusersuserIdcardsDataTokens} from './model/PaymentscardsusersuserIdcardsDataTokens';
import {UserIdCardsBody} from './model/UserIdCardsBody';
import {UsersLoginBody} from './model/UsersLoginBody';
import {UsersRegisterBody} from './model/UsersRegisterBody';
import {UsersRequestcodeBody} from './model/UsersRequestcodeBody';
import {MerchantApplicationApi} from './api/MerchantApplicationApi';
import {UsersApi} from './api/UsersApi';

/**
* API_Gateway.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiGateway = require('index'); // See note below*.
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001Data model constructor.
     * @property {module:model/InlineResponse2001Data}
     */
    InlineResponse2001Data,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007IdentityProviders model constructor.
     * @property {module:model/InlineResponse2007IdentityProviders}
     */
    InlineResponse2007IdentityProviders,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse401 model constructor.
     * @property {module:model/InlineResponse401}
     */
    InlineResponse401,

    /**
     * The InlineResponse4011 model constructor.
     * @property {module:model/InlineResponse4011}
     */
    InlineResponse4011,

    /**
     * The MerchantIdApplicationsBody model constructor.
     * @property {module:model/MerchantIdApplicationsBody}
     */
    MerchantIdApplicationsBody,

    /**
     * The PaymentscardsusersuserIdcardsData model constructor.
     * @property {module:model/PaymentscardsusersuserIdcardsData}
     */
    PaymentscardsusersuserIdcardsData,

    /**
     * The PaymentscardsusersuserIdcardsDataTokens model constructor.
     * @property {module:model/PaymentscardsusersuserIdcardsDataTokens}
     */
    PaymentscardsusersuserIdcardsDataTokens,

    /**
     * The UserIdCardsBody model constructor.
     * @property {module:model/UserIdCardsBody}
     */
    UserIdCardsBody,

    /**
     * The UsersLoginBody model constructor.
     * @property {module:model/UsersLoginBody}
     */
    UsersLoginBody,

    /**
     * The UsersRegisterBody model constructor.
     * @property {module:model/UsersRegisterBody}
     */
    UsersRegisterBody,

    /**
     * The UsersRequestcodeBody model constructor.
     * @property {module:model/UsersRequestcodeBody}
     */
    UsersRequestcodeBody,

    /**
    * The MerchantApplicationApi service constructor.
    * @property {module:api/MerchantApplicationApi}
    */
    MerchantApplicationApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
