/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import MerchantsExternalOrdersOrderTokenCouponsPost200Response from './model/MerchantsExternalOrdersOrderTokenCouponsPost200Response';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInner from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInner';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTaxAmount from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTaxAmount';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTotalAmount from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTotalAmount';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingAddress from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingAddress';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptions from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptions';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetails from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetails';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsContact from './model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsContact';
import MerchantsExternalOrdersOrderTokenCouponsPostRequest from './model/MerchantsExternalOrdersOrderTokenCouponsPostRequest';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200Response from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200Response';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInner from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInner';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInner from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInner';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTaxAmount from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTaxAmount';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTotalAmount from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTotalAmount';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerWeight from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerWeight';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderMetadata from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderMetadata';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingAddress from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingAddress';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptions from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptions';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetails from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetails';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsContact from './model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsContact';
import MerchantsExternalOrdersOrderTokenGiftCardsPostRequest from './model/MerchantsExternalOrdersOrderTokenGiftCardsPostRequest';
import MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200Response from './model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200Response';
import MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrder from './model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrder';
import MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrderShippingOptions from './model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrderShippingOptions';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingAddress from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingAddress';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner';
import MerchantsExternalOrdersOrderTokenShippingMethodsPostRequest from './model/MerchantsExternalOrdersOrderTokenShippingMethodsPostRequest';
import MerchantsExternalOrdersOrderTokenShippingRatePost200Response from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200Response';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseShippingOption from './model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseShippingOption';
import MerchantsExternalOrdersOrderTokenShippingRatePostRequest from './model/MerchantsExternalOrdersOrderTokenShippingRatePostRequest';
import MerchantsOrdersOrderTokenPaymentsMethodsGet200Response from './model/MerchantsOrdersOrderTokenPaymentsMethodsGet200Response';
import MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner from './model/MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner';
import MerchantsOrdersOrderTokenTransactionsVerifyPost200Response from './model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response';
import MerchantsOrdersOrderTokenTransactionsVerifyPostRequest from './model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest';
import MerchantsOrdersPostRequest from './model/MerchantsOrdersPostRequest';
import MerchantsOrdersPostRequestOrder from './model/MerchantsOrdersPostRequestOrder';
import MerchantsOrdersPostRequestOrderDiscountsInner from './model/MerchantsOrdersPostRequestOrderDiscountsInner';
import MerchantsOrdersPostRequestOrderItemsInner from './model/MerchantsOrdersPostRequestOrderItemsInner';
import MerchantsOrdersPostRequestOrderItemsInnerTotalAmount from './model/MerchantsOrdersPostRequestOrderItemsInnerTotalAmount';
import MerchantsOrdersPostRequestOrderShippingAddress from './model/MerchantsOrdersPostRequestOrderShippingAddress';
import MerchantsOrdersPostRequestOrderShippingOptions from './model/MerchantsOrdersPostRequestOrderShippingOptions';
import MerchantsOrdersPostRequestOrderShippingOptionsDetails from './model/MerchantsOrdersPostRequestOrderShippingOptionsDetails';
import MerchantsOrdersPostRequestOrderShippingOptionsDetailsContact from './model/MerchantsOrdersPostRequestOrderShippingOptionsDetailsContact';
import MerchantsTransactionsPurchasePost200Response from './model/MerchantsTransactionsPurchasePost200Response';
import MerchantsTransactionsPurchasePost200ResponseOrder from './model/MerchantsTransactionsPurchasePost200ResponseOrder';
import MerchantsTransactionsPurchasePost200ResponseOrderItemsInner from './model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInner';
import MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTaxAmount from './model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTaxAmount';
import MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTotalAmount from './model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTotalAmount';
import MerchantsTransactionsPurchasePost200ResponseOrderPayment from './model/MerchantsTransactionsPurchasePost200ResponseOrderPayment';
import MerchantsTransactionsPurchasePost200ResponseOrderPaymentData from './model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentData';
import MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount from './model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount';
import MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer from './model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer';
import MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard from './model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard';
import MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataMerchant from './model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataMerchant';
import MerchantsTransactionsPurchasePostRequest from './model/MerchantsTransactionsPurchasePostRequest';
import MerchantsTransactionsPurchasePostRequestCreditCard from './model/MerchantsTransactionsPurchasePostRequestCreditCard';
import MerchantsTransactionsPurchasePostRequestSpecificFields from './model/MerchantsTransactionsPurchasePostRequestSpecificFields';
import UsersLoginDeviceFingerprintPost200Response from './model/UsersLoginDeviceFingerprintPost200Response';
import UsersMeGet200Response from './model/UsersMeGet200Response';
import UsersMeGet200ResponseIdentityProvidersInner from './model/UsersMeGet200ResponseIdentityProvidersInner';
import ExternalMerchantAPIApi from './api/ExternalMerchantAPIApi';
import UsersApi from './api/UsersApi';


/**
* API Gateway.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiGateway = require('index'); // See note below*.
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiGateway.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiGateway.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200Response model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200Response}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200Response,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInner}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTaxAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTaxAmount}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTaxAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTotalAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTotalAmount}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerTotalAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderItemsInnerWeight,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingAddress model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingAddress}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingAddress,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptions model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptions}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptions,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetails model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetails}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetails,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsContact}
     */
    MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderShippingOptionsDetailsContact,

    /**
     * The MerchantsExternalOrdersOrderTokenCouponsPostRequest model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenCouponsPostRequest}
     */
    MerchantsExternalOrdersOrderTokenCouponsPostRequest,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200Response model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200Response}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200Response,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInner}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderDiscountsInnerFreeShipping,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInner}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTaxAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTaxAmount}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTaxAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTotalAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTotalAmount}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerTotalAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerWeight model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerWeight}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderItemsInnerWeight,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderMetadata model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderMetadata}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderMetadata,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingAddress model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingAddress}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingAddress,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptions model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptions}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptions,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetails model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetails}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetails,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAdditionalDetails,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsAddressCoordinates,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsContact}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderShippingOptionsDetailsContact,

    /**
     * The MerchantsExternalOrdersOrderTokenGiftCardsPostRequest model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPostRequest}
     */
    MerchantsExternalOrdersOrderTokenGiftCardsPostRequest,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200Response model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200Response}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200Response,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrder model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrder}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrder,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrderShippingOptions model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrderShippingOptions}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsCodePatch200ResponseOrderShippingOptions,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingAddress model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingAddress}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingAddress,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingMethodsPostRequest model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPostRequest}
     */
    MerchantsExternalOrdersOrderTokenShippingMethodsPostRequest,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200Response model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200Response}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200Response,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTaxAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInnerTotalAmount,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseShippingOption model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseShippingOption}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseShippingOption,

    /**
     * The MerchantsExternalOrdersOrderTokenShippingRatePostRequest model constructor.
     * @property {module:model/MerchantsExternalOrdersOrderTokenShippingRatePostRequest}
     */
    MerchantsExternalOrdersOrderTokenShippingRatePostRequest,

    /**
     * The MerchantsOrdersOrderTokenPaymentsMethodsGet200Response model constructor.
     * @property {module:model/MerchantsOrdersOrderTokenPaymentsMethodsGet200Response}
     */
    MerchantsOrdersOrderTokenPaymentsMethodsGet200Response,

    /**
     * The MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner model constructor.
     * @property {module:model/MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner}
     */
    MerchantsOrdersOrderTokenPaymentsMethodsGet200ResponseDataInner,

    /**
     * The MerchantsOrdersOrderTokenTransactionsVerifyPost200Response model constructor.
     * @property {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response}
     */
    MerchantsOrdersOrderTokenTransactionsVerifyPost200Response,

    /**
     * The MerchantsOrdersOrderTokenTransactionsVerifyPostRequest model constructor.
     * @property {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest}
     */
    MerchantsOrdersOrderTokenTransactionsVerifyPostRequest,

    /**
     * The MerchantsOrdersPostRequest model constructor.
     * @property {module:model/MerchantsOrdersPostRequest}
     */
    MerchantsOrdersPostRequest,

    /**
     * The MerchantsOrdersPostRequestOrder model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrder}
     */
    MerchantsOrdersPostRequestOrder,

    /**
     * The MerchantsOrdersPostRequestOrderDiscountsInner model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderDiscountsInner}
     */
    MerchantsOrdersPostRequestOrderDiscountsInner,

    /**
     * The MerchantsOrdersPostRequestOrderItemsInner model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderItemsInner}
     */
    MerchantsOrdersPostRequestOrderItemsInner,

    /**
     * The MerchantsOrdersPostRequestOrderItemsInnerTotalAmount model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderItemsInnerTotalAmount}
     */
    MerchantsOrdersPostRequestOrderItemsInnerTotalAmount,

    /**
     * The MerchantsOrdersPostRequestOrderShippingAddress model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderShippingAddress}
     */
    MerchantsOrdersPostRequestOrderShippingAddress,

    /**
     * The MerchantsOrdersPostRequestOrderShippingOptions model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderShippingOptions}
     */
    MerchantsOrdersPostRequestOrderShippingOptions,

    /**
     * The MerchantsOrdersPostRequestOrderShippingOptionsDetails model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderShippingOptionsDetails}
     */
    MerchantsOrdersPostRequestOrderShippingOptionsDetails,

    /**
     * The MerchantsOrdersPostRequestOrderShippingOptionsDetailsContact model constructor.
     * @property {module:model/MerchantsOrdersPostRequestOrderShippingOptionsDetailsContact}
     */
    MerchantsOrdersPostRequestOrderShippingOptionsDetailsContact,

    /**
     * The MerchantsTransactionsPurchasePost200Response model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200Response}
     */
    MerchantsTransactionsPurchasePost200Response,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrder model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrder}
     */
    MerchantsTransactionsPurchasePost200ResponseOrder,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderItemsInner model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInner}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderItemsInner,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTaxAmount model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTaxAmount}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTaxAmount,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTotalAmount model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTotalAmount}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderItemsInnerTotalAmount,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPayment model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPayment}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPayment,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentData model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentData}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPaymentData,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard,

    /**
     * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataMerchant model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataMerchant}
     */
    MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataMerchant,

    /**
     * The MerchantsTransactionsPurchasePostRequest model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePostRequest}
     */
    MerchantsTransactionsPurchasePostRequest,

    /**
     * The MerchantsTransactionsPurchasePostRequestCreditCard model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePostRequestCreditCard}
     */
    MerchantsTransactionsPurchasePostRequestCreditCard,

    /**
     * The MerchantsTransactionsPurchasePostRequestSpecificFields model constructor.
     * @property {module:model/MerchantsTransactionsPurchasePostRequestSpecificFields}
     */
    MerchantsTransactionsPurchasePostRequestSpecificFields,

    /**
     * The UsersLoginDeviceFingerprintPost200Response model constructor.
     * @property {module:model/UsersLoginDeviceFingerprintPost200Response}
     */
    UsersLoginDeviceFingerprintPost200Response,

    /**
     * The UsersMeGet200Response model constructor.
     * @property {module:model/UsersMeGet200Response}
     */
    UsersMeGet200Response,

    /**
     * The UsersMeGet200ResponseIdentityProvidersInner model constructor.
     * @property {module:model/UsersMeGet200ResponseIdentityProvidersInner}
     */
    UsersMeGet200ResponseIdentityProvidersInner,

    /**
    * The ExternalMerchantAPIApi service constructor.
    * @property {module:api/ExternalMerchantAPIApi}
    */
    ExternalMerchantAPIApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
