/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.apigw_kotlin_sdk.models

import io.deuna.apigw_kotlin_sdk.models.PurchaseRequestBillingAddress
import io.deuna.apigw_kotlin_sdk.models.PurchaseRequestBrowserDetails
import io.deuna.apigw_kotlin_sdk.models.PurchaseRequestCreditCard
import io.deuna.apigw_kotlin_sdk.models.PurchaseRequestShippingAddress
import io.deuna.apigw_kotlin_sdk.models.PurchaseRequestSpecificFields

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param processorName 
 * @param token 
 * @param billingAddress 
 * @param browserDetails 
 * @param captchaToken 
 * @param creditCard 
 * @param deviceId 
 * @param email 
 * @param installments 
 * @param methodType 
 * @param shippingAddress 
 * @param specificFields 
 * @param storeCode 
 */


data class PurchaseRequest (

    @Json(name = "processor_name")
    var processorName: kotlin.String,

    @Json(name = "token")
    var token: kotlin.String,

    @Json(name = "billing_address")
    var billingAddress: PurchaseRequestBillingAddress? = null,

    @Json(name = "browser_details")
    var browserDetails: PurchaseRequestBrowserDetails? = null,

    @Json(name = "captcha_token")
    var captchaToken: kotlin.String? = null,

    @Json(name = "credit_card")
    var creditCard: PurchaseRequestCreditCard? = null,

    @Json(name = "device_id")
    var deviceId: kotlin.String? = null,

    @Json(name = "email")
    var email: kotlin.String? = null,

    @Json(name = "installments")
    var installments: kotlin.Int? = null,

    @Json(name = "method_type")
    var methodType: kotlin.String? = null,

    @Json(name = "shipping_address")
    var shippingAddress: PurchaseRequestShippingAddress? = null,

    @Json(name = "specific_fields")
    var specificFields: PurchaseRequestSpecificFields? = null,

    @Json(name = "store_code")
    var storeCode: kotlin.String? = null

)

