/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.apigw_kotlin_sdk.models

import io.deuna.apigw_kotlin_sdk.models.Purchase200ResponseOrderItemsInnerTaxAmount
import io.deuna.apigw_kotlin_sdk.models.Purchase200ResponseOrderItemsInnerTotalAmount
import io.deuna.apigw_kotlin_sdk.models.Purchase200ResponseOrderItemsInnerWeight

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param brand 
 * @param category 
 * @param color 
 * @param description 
 * @param detailsUrl 
 * @param id 
 * @param imageUrl 
 * @param includedInSubscription 
 * @param isbn 
 * @param manufacturer 
 * @param name 
 * @param options 
 * @param quantity 
 * @param propertySize 
 * @param sku 
 * @param subscriptionId 
 * @param taxAmount 
 * @param taxable 
 * @param totalAmount 
 * @param type 
 * @param unitPrice 
 * @param uom 
 * @param upc 
 * @param weight 
 */


data class Purchase200ResponseOrderItemsInner (

    @Json(name = "brand")
    var brand: kotlin.String? = null,

    @Json(name = "category")
    var category: kotlin.String? = null,

    @Json(name = "color")
    var color: kotlin.String? = null,

    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "details_url")
    var detailsUrl: kotlin.String? = null,

    @Json(name = "id")
    var id: kotlin.String? = null,

    @Json(name = "image_url")
    var imageUrl: kotlin.String? = null,

    @Json(name = "included_in_subscription")
    var includedInSubscription: kotlin.Boolean? = null,

    @Json(name = "isbn")
    var isbn: kotlin.String? = null,

    @Json(name = "manufacturer")
    var manufacturer: kotlin.String? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "options")
    var options: kotlin.String? = null,

    @Json(name = "quantity")
    var quantity: kotlin.Int? = null,

    @Json(name = "size")
    var propertySize: kotlin.String? = null,

    @Json(name = "sku")
    var sku: kotlin.String? = null,

    @Json(name = "subscription_id")
    var subscriptionId: kotlin.String? = null,

    @Json(name = "tax_amount")
    var taxAmount: Purchase200ResponseOrderItemsInnerTaxAmount? = null,

    @Json(name = "taxable")
    var taxable: kotlin.Boolean? = null,

    @Json(name = "total_amount")
    var totalAmount: Purchase200ResponseOrderItemsInnerTotalAmount? = null,

    @Json(name = "type")
    var type: kotlin.String? = null,

    @Json(name = "unit_price")
    var unitPrice: Purchase200ResponseOrderItemsInnerTaxAmount? = null,

    @Json(name = "uom")
    var uom: kotlin.String? = null,

    @Json(name = "upc")
    var upc: kotlin.String? = null,

    @Json(name = "weight")
    var weight: Purchase200ResponseOrderItemsInnerWeight? = null

)

