/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.apigw_kotlin_sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param screenHeight 
 * @param screenWidth 
 */


data class PurchaseRequestBrowserDetails (

    @Json(name = "screen_height")
    var screenHeight: kotlin.Int? = null,

    @Json(name = "screen_width")
    var screenWidth: kotlin.Int? = null

)

