/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiGateway);
  }
}(this, function(expect, ApiGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner', function() {
    it('should create an instance of MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner', function() {
      // uncomment below and update the code to test MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be.a(ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner);
    });

    it('should have the property brand (base name: "brand")', function() {
      // uncomment below and update the code to test the property brand
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property detailsUrl (base name: "details_url")', function() {
      // uncomment below and update the code to test the property detailsUrl
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property isbn (base name: "isbn")', function() {
      // uncomment below and update the code to test the property isbn
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property manufacturer (base name: "manufacturer")', function() {
      // uncomment below and update the code to test the property manufacturer
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property taxAmount (base name: "tax_amount")', function() {
      // uncomment below and update the code to test the property taxAmount
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property taxable (base name: "taxable")', function() {
      // uncomment below and update the code to test the property taxable
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "total_amount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property unitPrice (base name: "unit_price")', function() {
      // uncomment below and update the code to test the property unitPrice
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property uom (base name: "uom")', function() {
      // uncomment below and update the code to test the property uom
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property upc (base name: "upc")', function() {
      // uncomment below and update the code to test the property upc
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new ApiGateway.MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner();
      //expect(instance).to.be();
    });

  });

}));
