/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2002 model module.
 * @module model/InlineResponse2002
 * @version 1.0
 */
export class InlineResponse2002 {
  /**
   * Constructs a new <code>InlineResponse2002</code>.
   * @alias module:model/InlineResponse2002
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('is_sandbox'))
        obj.isSandbox = ApiClient.convertToType(data['is_sandbox'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('private_key'))
        obj.privateKey = ApiClient.convertToType(data['private_key'], 'String');
      if (data.hasOwnProperty('public_key'))
        obj.publicKey = ApiClient.convertToType(data['public_key'], 'String');
      if (data.hasOwnProperty('signing_secret'))
        obj.signingSecret = ApiClient.convertToType(data['signing_secret'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} createdAt
 */
InlineResponse2002.prototype.createdAt = undefined;

/**
 * @member {String} id
 */
InlineResponse2002.prototype.id = undefined;

/**
 * @member {Boolean} isSandbox
 */
InlineResponse2002.prototype.isSandbox = undefined;

/**
 * @member {String} name
 */
InlineResponse2002.prototype.name = undefined;

/**
 * @member {String} privateKey
 */
InlineResponse2002.prototype.privateKey = undefined;

/**
 * @member {String} publicKey
 */
InlineResponse2002.prototype.publicKey = undefined;

/**
 * @member {String} signingSecret
 */
InlineResponse2002.prototype.signingSecret = undefined;

/**
 * @member {String} status
 */
InlineResponse2002.prototype.status = undefined;

/**
 * @member {String} updatedAt
 */
InlineResponse2002.prototype.updatedAt = undefined;

