/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2001Data model module.
 * @module model/InlineResponse2001Data
 * @version 1.0
 */
export class InlineResponse2001Data {
  /**
   * Constructs a new <code>InlineResponse2001Data</code>.
   * @alias module:model/InlineResponse2001Data
   * @class
   * @param createdAt {String} 
   * @param id {String} 
   * @param isSandbox {Boolean} 
   * @param name {String} 
   * @param status {String} 
   * @param updatedAt {String} 
   */
  constructor(createdAt, id, isSandbox, name, status, updatedAt) {
    this.createdAt = createdAt;
    this.id = id;
    this.isSandbox = isSandbox;
    this.name = name;
    this.status = status;
    this.updatedAt = updatedAt;
  }

  /**
   * Constructs a <code>InlineResponse2001Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001Data} The populated <code>InlineResponse2001Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001Data();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('is_sandbox'))
        obj.isSandbox = ApiClient.convertToType(data['is_sandbox'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} createdAt
 */
InlineResponse2001Data.prototype.createdAt = undefined;

/**
 * @member {String} id
 */
InlineResponse2001Data.prototype.id = undefined;

/**
 * @member {Boolean} isSandbox
 */
InlineResponse2001Data.prototype.isSandbox = undefined;

/**
 * @member {String} name
 */
InlineResponse2001Data.prototype.name = undefined;

/**
 * @member {String} status
 */
InlineResponse2001Data.prototype.status = undefined;

/**
 * @member {String} updatedAt
 */
InlineResponse2001Data.prototype.updatedAt = undefined;

