/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2007IdentityProviders model module.
 * @module model/InlineResponse2007IdentityProviders
 * @version 1.0
 */
export class InlineResponse2007IdentityProviders {
  /**
   * Constructs a new <code>InlineResponse2007IdentityProviders</code>.
   * @alias module:model/InlineResponse2007IdentityProviders
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2007IdentityProviders</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007IdentityProviders} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007IdentityProviders} The populated <code>InlineResponse2007IdentityProviders</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007IdentityProviders();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('deleted_at'))
        obj.deletedAt = ApiClient.convertToType(data['deleted_at'], Object);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('provider_name'))
        obj.providerName = ApiClient.convertToType(data['provider_name'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} createdAt
 */
InlineResponse2007IdentityProviders.prototype.createdAt = undefined;

/**
 * @member {Object} deletedAt
 */
InlineResponse2007IdentityProviders.prototype.deletedAt = undefined;

/**
 * @member {Number} id
 */
InlineResponse2007IdentityProviders.prototype.id = undefined;

/**
 * @member {String} providerName
 */
InlineResponse2007IdentityProviders.prototype.providerName = undefined;

/**
 * @member {String} updatedAt
 */
InlineResponse2007IdentityProviders.prototype.updatedAt = undefined;

