/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2007IdentityProviders} from './InlineResponse2007IdentityProviders';

/**
 * The InlineResponse2007 model module.
 * @module model/InlineResponse2007
 * @version 1.0
 */
export class InlineResponse2007 {
  /**
   * Constructs a new <code>InlineResponse2007</code>.
   * @alias module:model/InlineResponse2007
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2007</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007} The populated <code>InlineResponse2007</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2007();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('deleted_at'))
        obj.deletedAt = ApiClient.convertToType(data['deleted_at'], Object);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('identity_providers'))
        obj.identityProviders = ApiClient.convertToType(data['identity_providers'], [InlineResponse2007IdentityProviders]);
      if (data.hasOwnProperty('is_guest'))
        obj.isGuest = ApiClient.convertToType(data['is_guest'], 'Boolean');
      if (data.hasOwnProperty('is_phone_verified'))
        obj.isPhoneVerified = ApiClient.convertToType(data['is_phone_verified'], 'Boolean');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('merchant_id'))
        obj.merchantId = ApiClient.convertToType(data['merchant_id'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} createdAt
 */
InlineResponse2007.prototype.createdAt = undefined;

/**
 * @member {Object} deletedAt
 */
InlineResponse2007.prototype.deletedAt = undefined;

/**
 * @member {String} email
 */
InlineResponse2007.prototype.email = undefined;

/**
 * @member {String} firstName
 */
InlineResponse2007.prototype.firstName = undefined;

/**
 * @member {String} id
 */
InlineResponse2007.prototype.id = undefined;

/**
 * @member {Array.<module:model/InlineResponse2007IdentityProviders>} identityProviders
 */
InlineResponse2007.prototype.identityProviders = undefined;

/**
 * @member {Boolean} isGuest
 */
InlineResponse2007.prototype.isGuest = undefined;

/**
 * @member {Boolean} isPhoneVerified
 */
InlineResponse2007.prototype.isPhoneVerified = undefined;

/**
 * @member {String} lastName
 */
InlineResponse2007.prototype.lastName = undefined;

/**
 * @member {String} merchantId
 */
InlineResponse2007.prototype.merchantId = undefined;

/**
 * @member {String} phone
 */
InlineResponse2007.prototype.phone = undefined;

/**
 * @member {String} updatedAt
 */
InlineResponse2007.prototype.updatedAt = undefined;

