/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails from './MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails';

/**
 * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions model module.
 * @module model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions</code>.
     * @alias module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions
     * @param details {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails} 
     * @param type {String} 
     */
    constructor(details, type) { 
        
        MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions.initialize(this, details, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, details, type) { 
        obj['details'] = details;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions} The populated <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions();

            if (data.hasOwnProperty('details')) {
                obj['details'] = MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `details`
        if (data['details']) { // data not null
          MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails.validateJSON(data['details']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions.RequiredProperties = ["details", "type"];

/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptionsDetails} details
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions.prototype['details'] = undefined;

/**
 * @member {String} type
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions.prototype['type'] = undefined;






export default MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderShippingOptions;

