/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder from './MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder';

/**
 * The MerchantsOrdersOrderTokenTransactionsVerifyPost200Response model module.
 * @module model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response
 * @version 1.0
 */
class MerchantsOrdersOrderTokenTransactionsVerifyPost200Response {
    /**
     * Constructs a new <code>MerchantsOrdersOrderTokenTransactionsVerifyPost200Response</code>.
     * 
     * @alias module:model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response
     */
    constructor() { 
        
        MerchantsOrdersOrderTokenTransactionsVerifyPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsOrdersOrderTokenTransactionsVerifyPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response} obj Optional instance to populate.
     * @return {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPost200Response} The populated <code>MerchantsOrdersOrderTokenTransactionsVerifyPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsOrdersOrderTokenTransactionsVerifyPost200Response();

            if (data.hasOwnProperty('order')) {
                obj['order'] = MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder.constructFromObject(data['order']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsOrdersOrderTokenTransactionsVerifyPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsOrdersOrderTokenTransactionsVerifyPost200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `order`
        if (data['order']) { // data not null
          MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder.validateJSON(data['order']);
        }

        return true;
    }


}



/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrder} order
 */
MerchantsOrdersOrderTokenTransactionsVerifyPost200Response.prototype['order'] = undefined;






export default MerchantsOrdersOrderTokenTransactionsVerifyPost200Response;

