/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsOrdersOrderTokenTransactionsVerifyPostRequest model module.
 * @module model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest
 * @version 1.0
 */
class MerchantsOrdersOrderTokenTransactionsVerifyPostRequest {
    /**
     * Constructs a new <code>MerchantsOrdersOrderTokenTransactionsVerifyPostRequest</code>.
     * 
     * @alias module:model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest
     */
    constructor() { 
        
        MerchantsOrdersOrderTokenTransactionsVerifyPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsOrdersOrderTokenTransactionsVerifyPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest} obj Optional instance to populate.
     * @return {module:model/MerchantsOrdersOrderTokenTransactionsVerifyPostRequest} The populated <code>MerchantsOrdersOrderTokenTransactionsVerifyPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsOrdersOrderTokenTransactionsVerifyPostRequest();

            if (data.hasOwnProperty('otp')) {
                obj['otp'] = ApiClient.convertToType(data['otp'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsOrdersOrderTokenTransactionsVerifyPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsOrdersOrderTokenTransactionsVerifyPostRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['otp'] && !(typeof data['otp'] === 'string' || data['otp'] instanceof String)) {
            throw new Error("Expected the field `otp` to be a primitive type in the JSON string but got " + data['otp']);
        }

        return true;
    }


}



/**
 * @member {String} otp
 */
MerchantsOrdersOrderTokenTransactionsVerifyPostRequest.prototype['otp'] = undefined;






export default MerchantsOrdersOrderTokenTransactionsVerifyPostRequest;

