/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount model module.
 * @module model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount
 * @version 1.0
 */
class MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount</code>.
     * @alias module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount
     * @param amount {Number} 
     * @param currency {String} 
     */
    constructor(amount, currency) { 
        
        MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount.initialize(this, amount, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, currency) { 
        obj['amount'] = amount;
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount} The populated <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount.RequiredProperties = ["amount", "currency"];

/**
 * @member {Number} amount
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount.prototype['currency'] = undefined;






export default MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataAmount;

