/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard model module.
 * @module model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard
 * @version 1.0
 */
class MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard</code>.
     * @alias module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard
     * @param cardBrand {String} 
     * @param firstSix {String} 
     * @param lastFour {String} 
     */
    constructor(cardBrand, firstSix, lastFour) { 
        
        MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.initialize(this, cardBrand, firstSix, lastFour);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cardBrand, firstSix, lastFour) { 
        obj['card_brand'] = cardBrand;
        obj['first_six'] = firstSix;
        obj['last_four'] = lastFour;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard} The populated <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard();

            if (data.hasOwnProperty('card_brand')) {
                obj['card_brand'] = ApiClient.convertToType(data['card_brand'], 'String');
            }
            if (data.hasOwnProperty('first_six')) {
                obj['first_six'] = ApiClient.convertToType(data['first_six'], 'String');
            }
            if (data.hasOwnProperty('last_four')) {
                obj['last_four'] = ApiClient.convertToType(data['last_four'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['card_brand'] && !(typeof data['card_brand'] === 'string' || data['card_brand'] instanceof String)) {
            throw new Error("Expected the field `card_brand` to be a primitive type in the JSON string but got " + data['card_brand']);
        }
        // ensure the json data is a string
        if (data['first_six'] && !(typeof data['first_six'] === 'string' || data['first_six'] instanceof String)) {
            throw new Error("Expected the field `first_six` to be a primitive type in the JSON string but got " + data['first_six']);
        }
        // ensure the json data is a string
        if (data['last_four'] && !(typeof data['last_four'] === 'string' || data['last_four'] instanceof String)) {
            throw new Error("Expected the field `last_four` to be a primitive type in the JSON string but got " + data['last_four']);
        }

        return true;
    }


}

MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.RequiredProperties = ["card_brand", "first_six", "last_four"];

/**
 * @member {String} card_brand
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.prototype['card_brand'] = undefined;

/**
 * @member {String} first_six
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.prototype['first_six'] = undefined;

/**
 * @member {String} last_four
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard.prototype['last_four'] = undefined;






export default MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataFromCard;

