/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping from './MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping';

/**
 * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner model module.
 * @module model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner</code>.
     * @alias module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner
     */
    constructor() { 
        
        MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner} The populated <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('details_url')) {
                obj['details_url'] = ApiClient.convertToType(data['details_url'], 'String');
            }
            if (data.hasOwnProperty('discount_category')) {
                obj['discount_category'] = ApiClient.convertToType(data['discount_category'], 'String');
            }
            if (data.hasOwnProperty('display_amount')) {
                obj['display_amount'] = ApiClient.convertToType(data['display_amount'], 'String');
            }
            if (data.hasOwnProperty('free_shipping')) {
                obj['free_shipping'] = MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping.constructFromObject(data['free_shipping']);
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['details_url'] && !(typeof data['details_url'] === 'string' || data['details_url'] instanceof String)) {
            throw new Error("Expected the field `details_url` to be a primitive type in the JSON string but got " + data['details_url']);
        }
        // ensure the json data is a string
        if (data['discount_category'] && !(typeof data['discount_category'] === 'string' || data['discount_category'] instanceof String)) {
            throw new Error("Expected the field `discount_category` to be a primitive type in the JSON string but got " + data['discount_category']);
        }
        // ensure the json data is a string
        if (data['display_amount'] && !(typeof data['display_amount'] === 'string' || data['display_amount'] instanceof String)) {
            throw new Error("Expected the field `display_amount` to be a primitive type in the JSON string but got " + data['display_amount']);
        }
        // validate the optional field `free_shipping`
        if (data['free_shipping']) { // data not null
          MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping.validateJSON(data['free_shipping']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }

        return true;
    }


}



/**
 * @member {Number} amount
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['amount'] = undefined;

/**
 * @member {String} code
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['code'] = undefined;

/**
 * @member {String} description
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['description'] = undefined;

/**
 * @member {String} details_url
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['details_url'] = undefined;

/**
 * @member {String} discount_category
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['discount_category'] = undefined;

/**
 * @member {String} display_amount
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['display_amount'] = undefined;

/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderDiscountsInnerFreeShipping} free_shipping
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['free_shipping'] = undefined;

/**
 * @member {String} reference
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner.prototype['reference'] = undefined;






export default MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrderDiscountsInner;

