/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer model module.
 * @module model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer
 * @version 1.0
 */
class MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer</code>.
     * @alias module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer
     * @param email {String} 
     * @param id {String} 
     */
    constructor(email, id) { 
        
        MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer.initialize(this, email, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, id) { 
        obj['email'] = email;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer} The populated <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer.RequiredProperties = ["email", "id"];

/**
 * @member {String} email
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer.prototype['email'] = undefined;

/**
 * @member {String} id
 */
MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer.prototype['id'] = undefined;






export default MerchantsTransactionsPurchasePost200ResponseOrderPaymentDataCustomer;

