/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder from './MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder';

/**
 * The MerchantsExternalOrdersOrderTokenCouponsPost200Response model module.
 * @module model/MerchantsExternalOrdersOrderTokenCouponsPost200Response
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenCouponsPost200Response {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenCouponsPost200Response</code>.
     * 
     * @alias module:model/MerchantsExternalOrdersOrderTokenCouponsPost200Response
     */
    constructor() { 
        
        MerchantsExternalOrdersOrderTokenCouponsPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenCouponsPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200Response} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200Response} The populated <code>MerchantsExternalOrdersOrderTokenCouponsPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenCouponsPost200Response();

            if (data.hasOwnProperty('order')) {
                obj['order'] = MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder.constructFromObject(data['order']);
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenCouponsPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenCouponsPost200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `order`
        if (data['order']) { // data not null
          MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder.validateJSON(data['order']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}



/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrder} order
 */
MerchantsExternalOrdersOrderTokenCouponsPost200Response.prototype['order'] = undefined;

/**
 * @member {String} token
 */
MerchantsExternalOrdersOrderTokenCouponsPost200Response.prototype['token'] = undefined;






export default MerchantsExternalOrdersOrderTokenCouponsPost200Response;

