/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder from './MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder';
import MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner from './MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner';

/**
 * The MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response model module.
 * @module model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response</code>.
     * 
     * @alias module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response
     */
    constructor() { 
        
        MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response} The populated <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response();

            if (data.hasOwnProperty('order')) {
                obj['order'] = MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder.constructFromObject(data['order']);
            }
            if (data.hasOwnProperty('shipping_methods')) {
                obj['shipping_methods'] = ApiClient.convertToType(data['shipping_methods'], [MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `order`
        if (data['order']) { // data not null
          MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder.validateJSON(data['order']);
        }
        if (data['shipping_methods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['shipping_methods'])) {
                throw new Error("Expected the field `shipping_methods` to be an array in the JSON data but got " + data['shipping_methods']);
            }
            // validate the optional field `shipping_methods` (array)
            for (const item of data['shipping_methods']) {
                MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseOrder} order
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response.prototype['order'] = undefined;

/**
 * @member {Array.<module:model/MerchantsExternalOrdersOrderTokenShippingMethodsPost200ResponseShippingMethodsInner>} shipping_methods
 */
MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response.prototype['shipping_methods'] = undefined;






export default MerchantsExternalOrdersOrderTokenShippingMethodsPost200Response;

