/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsTransactionsPurchasePostRequestSpecificFields model module.
 * @module model/MerchantsTransactionsPurchasePostRequestSpecificFields
 * @version 1.0
 */
class MerchantsTransactionsPurchasePostRequestSpecificFields {
    /**
     * Constructs a new <code>MerchantsTransactionsPurchasePostRequestSpecificFields</code>.
     * @alias module:model/MerchantsTransactionsPurchasePostRequestSpecificFields
     * @param financialInstitution {String} 
     */
    constructor(financialInstitution) { 
        
        MerchantsTransactionsPurchasePostRequestSpecificFields.initialize(this, financialInstitution);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, financialInstitution) { 
        obj['financial_institution'] = financialInstitution;
    }

    /**
     * Constructs a <code>MerchantsTransactionsPurchasePostRequestSpecificFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsTransactionsPurchasePostRequestSpecificFields} obj Optional instance to populate.
     * @return {module:model/MerchantsTransactionsPurchasePostRequestSpecificFields} The populated <code>MerchantsTransactionsPurchasePostRequestSpecificFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsTransactionsPurchasePostRequestSpecificFields();

            if (data.hasOwnProperty('financial_institution')) {
                obj['financial_institution'] = ApiClient.convertToType(data['financial_institution'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsTransactionsPurchasePostRequestSpecificFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsTransactionsPurchasePostRequestSpecificFields</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsTransactionsPurchasePostRequestSpecificFields.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['financial_institution'] && !(typeof data['financial_institution'] === 'string' || data['financial_institution'] instanceof String)) {
            throw new Error("Expected the field `financial_institution` to be a primitive type in the JSON string but got " + data['financial_institution']);
        }

        return true;
    }


}

MerchantsTransactionsPurchasePostRequestSpecificFields.RequiredProperties = ["financial_institution"];

/**
 * @member {String} financial_institution
 */
MerchantsTransactionsPurchasePostRequestSpecificFields.prototype['financial_institution'] = undefined;






export default MerchantsTransactionsPurchasePostRequestSpecificFields;

