/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata from './MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner from './MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner from './MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress from './MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress';

/**
 * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder model module.
 * @module model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder</code>.
     * @alias module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder
     * @param currency {String} 
     * @param discounts {Array.<module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner>} 
     * @param items {Array.<module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner>} 
     * @param itemsTotalAmount {Number} 
     * @param metadata {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata} 
     * @param orderId {String} 
     * @param shippingAddress {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress} 
     * @param shippingAmount {Number} 
     * @param storeCode {String} 
     * @param subTotal {Number} 
     * @param taxAmount {Number} 
     * @param totalAmount {Number} 
     * @param userInstructions {String} 
     */
    constructor(currency, discounts, items, itemsTotalAmount, metadata, orderId, shippingAddress, shippingAmount, storeCode, subTotal, taxAmount, totalAmount, userInstructions) { 
        
        MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.initialize(this, currency, discounts, items, itemsTotalAmount, metadata, orderId, shippingAddress, shippingAmount, storeCode, subTotal, taxAmount, totalAmount, userInstructions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency, discounts, items, itemsTotalAmount, metadata, orderId, shippingAddress, shippingAmount, storeCode, subTotal, taxAmount, totalAmount, userInstructions) { 
        obj['currency'] = currency;
        obj['discounts'] = discounts;
        obj['items'] = items;
        obj['items_total_amount'] = itemsTotalAmount;
        obj['metadata'] = metadata;
        obj['order_id'] = orderId;
        obj['shipping_address'] = shippingAddress;
        obj['shipping_amount'] = shippingAmount;
        obj['store_code'] = storeCode;
        obj['sub_total'] = subTotal;
        obj['tax_amount'] = taxAmount;
        obj['total_amount'] = totalAmount;
        obj['user_instructions'] = userInstructions;
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder} The populated <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('discounts')) {
                obj['discounts'] = ApiClient.convertToType(data['discounts'], [MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner]);
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner]);
            }
            if (data.hasOwnProperty('items_total_amount')) {
                obj['items_total_amount'] = ApiClient.convertToType(data['items_total_amount'], 'Number');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
            }
            if (data.hasOwnProperty('shipping_address')) {
                obj['shipping_address'] = MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress.constructFromObject(data['shipping_address']);
            }
            if (data.hasOwnProperty('shipping_amount')) {
                obj['shipping_amount'] = ApiClient.convertToType(data['shipping_amount'], 'Number');
            }
            if (data.hasOwnProperty('store_code')) {
                obj['store_code'] = ApiClient.convertToType(data['store_code'], 'String');
            }
            if (data.hasOwnProperty('sub_total')) {
                obj['sub_total'] = ApiClient.convertToType(data['sub_total'], 'Number');
            }
            if (data.hasOwnProperty('tax_amount')) {
                obj['tax_amount'] = ApiClient.convertToType(data['tax_amount'], 'Number');
            }
            if (data.hasOwnProperty('total_amount')) {
                obj['total_amount'] = ApiClient.convertToType(data['total_amount'], 'Number');
            }
            if (data.hasOwnProperty('user_instructions')) {
                obj['user_instructions'] = ApiClient.convertToType(data['user_instructions'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        if (data['discounts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['discounts'])) {
                throw new Error("Expected the field `discounts` to be an array in the JSON data but got " + data['discounts']);
            }
            // validate the optional field `discounts` (array)
            for (const item of data['discounts']) {
                MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.validateJsonObject(item);
            };
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner.validateJsonObject(item);
            };
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata.validateJSON(data['metadata']);
        }
        // ensure the json data is a string
        if (data['order_id'] && !(typeof data['order_id'] === 'string' || data['order_id'] instanceof String)) {
            throw new Error("Expected the field `order_id` to be a primitive type in the JSON string but got " + data['order_id']);
        }
        // validate the optional field `shipping_address`
        if (data['shipping_address']) { // data not null
          MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress.validateJSON(data['shipping_address']);
        }
        // ensure the json data is a string
        if (data['store_code'] && !(typeof data['store_code'] === 'string' || data['store_code'] instanceof String)) {
            throw new Error("Expected the field `store_code` to be a primitive type in the JSON string but got " + data['store_code']);
        }
        // ensure the json data is a string
        if (data['user_instructions'] && !(typeof data['user_instructions'] === 'string' || data['user_instructions'] instanceof String)) {
            throw new Error("Expected the field `user_instructions` to be a primitive type in the JSON string but got " + data['user_instructions']);
        }

        return true;
    }


}

MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.RequiredProperties = ["currency", "discounts", "items", "items_total_amount", "metadata", "order_id", "shipping_address", "shipping_amount", "store_code", "sub_total", "tax_amount", "total_amount", "user_instructions"];

/**
 * @member {String} currency
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['currency'] = undefined;

/**
 * @member {Array.<module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner>} discounts
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['discounts'] = undefined;

/**
 * @member {Array.<module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderItemsInner>} items
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['items'] = undefined;

/**
 * @member {Number} items_total_amount
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['items_total_amount'] = undefined;

/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenCouponsPost200ResponseOrderMetadata} metadata
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['metadata'] = undefined;

/**
 * @member {String} order_id
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['order_id'] = undefined;

/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderShippingAddress} shipping_address
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['shipping_address'] = undefined;

/**
 * @member {Number} shipping_amount
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['shipping_amount'] = undefined;

/**
 * @member {String} store_code
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['store_code'] = undefined;

/**
 * @member {Number} sub_total
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['sub_total'] = undefined;

/**
 * @member {Number} tax_amount
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['tax_amount'] = undefined;

/**
 * @member {Number} total_amount
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['total_amount'] = undefined;

/**
 * @member {String} user_instructions
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder.prototype['user_instructions'] = undefined;






export default MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrder;

