/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping from './MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping';

/**
 * The MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner model module.
 * @module model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner</code>.
     * @alias module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner
     * @param amount {Number} 
     * @param code {String} 
     * @param description {String} 
     * @param detailsUrl {String} 
     * @param discountCategory {String} 
     * @param reference {String} 
     */
    constructor(amount, code, description, detailsUrl, discountCategory, reference) { 
        
        MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.initialize(this, amount, code, description, detailsUrl, discountCategory, reference);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, code, description, detailsUrl, discountCategory, reference) { 
        obj['amount'] = amount;
        obj['code'] = code;
        obj['description'] = description;
        obj['details_url'] = detailsUrl;
        obj['discount_category'] = discountCategory;
        obj['reference'] = reference;
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner} The populated <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('details_url')) {
                obj['details_url'] = ApiClient.convertToType(data['details_url'], 'String');
            }
            if (data.hasOwnProperty('discount_category')) {
                obj['discount_category'] = ApiClient.convertToType(data['discount_category'], 'String');
            }
            if (data.hasOwnProperty('free_shipping')) {
                obj['free_shipping'] = MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping.constructFromObject(data['free_shipping']);
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['details_url'] && !(typeof data['details_url'] === 'string' || data['details_url'] instanceof String)) {
            throw new Error("Expected the field `details_url` to be a primitive type in the JSON string but got " + data['details_url']);
        }
        // ensure the json data is a string
        if (data['discount_category'] && !(typeof data['discount_category'] === 'string' || data['discount_category'] instanceof String)) {
            throw new Error("Expected the field `discount_category` to be a primitive type in the JSON string but got " + data['discount_category']);
        }
        // validate the optional field `free_shipping`
        if (data['free_shipping']) { // data not null
          MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping.validateJSON(data['free_shipping']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }

        return true;
    }


}

MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.RequiredProperties = ["amount", "code", "description", "details_url", "discount_category", "reference"];

/**
 * @member {Number} amount
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['amount'] = undefined;

/**
 * @member {String} code
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['code'] = undefined;

/**
 * @member {String} description
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['description'] = undefined;

/**
 * @member {String} details_url
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['details_url'] = undefined;

/**
 * @member {String} discount_category
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['discount_category'] = undefined;

/**
 * @member {module:model/MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInnerFreeShipping} free_shipping
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['free_shipping'] = undefined;

/**
 * @member {String} reference
 */
MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner.prototype['reference'] = undefined;






export default MerchantsExternalOrdersOrderTokenShippingRatePost200ResponseOrderDiscountsInner;

