/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner model module.
 * @module model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner
 * @version 1.0
 */
class MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner {
    /**
     * Constructs a new <code>MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner</code>.
     * @alias module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner
     */
    constructor() { 
        
        MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner} obj Optional instance to populate.
     * @return {module:model/MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner} The populated <code>MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('details_url')) {
                obj['details_url'] = ApiClient.convertToType(data['details_url'], 'String');
            }
            if (data.hasOwnProperty('display_amount')) {
                obj['display_amount'] = ApiClient.convertToType(data['display_amount'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['details_url'] && !(typeof data['details_url'] === 'string' || data['details_url'] instanceof String)) {
            throw new Error("Expected the field `details_url` to be a primitive type in the JSON string but got " + data['details_url']);
        }
        // ensure the json data is a string
        if (data['display_amount'] && !(typeof data['display_amount'] === 'string' || data['display_amount'] instanceof String)) {
            throw new Error("Expected the field `display_amount` to be a primitive type in the JSON string but got " + data['display_amount']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }

        return true;
    }


}



/**
 * @member {Number} amount
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['amount'] = undefined;

/**
 * @member {String} code
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['code'] = undefined;

/**
 * @member {String} description
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['description'] = undefined;

/**
 * @member {String} details_url
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['details_url'] = undefined;

/**
 * @member {String} display_amount
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['display_amount'] = undefined;

/**
 * @member {String} reference
 */
MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner.prototype['reference'] = undefined;






export default MerchantsExternalOrdersOrderTokenGiftCardsPost200ResponseOrderGiftCardInner;

