/*
 * API Gateway
 * API Gateway
 *
 * OpenAPI spec version: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.44
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UsersRegisterBody model module.
 * @module model/UsersRegisterBody
 * @version 1.0
 */
export class UsersRegisterBody {
  /**
   * Constructs a new <code>UsersRegisterBody</code>.
   * @alias module:model/UsersRegisterBody
   * @class
   * @param email {String} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param phone {String} 
   */
  constructor(email, firstName, lastName, phone) {
    this.email = email;
    this.firstName = firstName;
    this.lastName = lastName;
    this.phone = phone;
  }

  /**
   * Constructs a <code>UsersRegisterBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersRegisterBody} obj Optional instance to populate.
   * @return {module:model/UsersRegisterBody} The populated <code>UsersRegisterBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsersRegisterBody();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('identity_document'))
        obj.identityDocument = ApiClient.convertToType(data['identity_document'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
UsersRegisterBody.prototype.email = undefined;

/**
 * @member {String} firstName
 */
UsersRegisterBody.prototype.firstName = undefined;

/**
 * @member {String} identityDocument
 */
UsersRegisterBody.prototype.identityDocument = undefined;

/**
 * @member {String} lastName
 */
UsersRegisterBody.prototype.lastName = undefined;

/**
 * @member {String} phone
 */
UsersRegisterBody.prototype.phone = undefined;

