/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersMeGet200ResponseIdentityProvidersInner model module.
 * @module model/UsersMeGet200ResponseIdentityProvidersInner
 * @version 1.0
 */
class UsersMeGet200ResponseIdentityProvidersInner {
    /**
     * Constructs a new <code>UsersMeGet200ResponseIdentityProvidersInner</code>.
     * @alias module:model/UsersMeGet200ResponseIdentityProvidersInner
     */
    constructor() { 
        
        UsersMeGet200ResponseIdentityProvidersInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsersMeGet200ResponseIdentityProvidersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersMeGet200ResponseIdentityProvidersInner} obj Optional instance to populate.
     * @return {module:model/UsersMeGet200ResponseIdentityProvidersInner} The populated <code>UsersMeGet200ResponseIdentityProvidersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersMeGet200ResponseIdentityProvidersInner();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('provider_name')) {
                obj['provider_name'] = ApiClient.convertToType(data['provider_name'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersMeGet200ResponseIdentityProvidersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersMeGet200ResponseIdentityProvidersInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['provider_name'] && !(typeof data['provider_name'] === 'string' || data['provider_name'] instanceof String)) {
            throw new Error("Expected the field `provider_name` to be a primitive type in the JSON string but got " + data['provider_name']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * @member {String} created_at
 */
UsersMeGet200ResponseIdentityProvidersInner.prototype['created_at'] = undefined;

/**
 * @member {Object} deleted_at
 */
UsersMeGet200ResponseIdentityProvidersInner.prototype['deleted_at'] = undefined;

/**
 * @member {Number} id
 */
UsersMeGet200ResponseIdentityProvidersInner.prototype['id'] = undefined;

/**
 * @member {String} provider_name
 */
UsersMeGet200ResponseIdentityProvidersInner.prototype['provider_name'] = undefined;

/**
 * @member {String} updated_at
 */
UsersMeGet200ResponseIdentityProvidersInner.prototype['updated_at'] = undefined;






export default UsersMeGet200ResponseIdentityProvidersInner;

