/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MerchantsMerchantIdApplicationsPostRequest
 */
export interface MerchantsMerchantIdApplicationsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsPostRequest
     */
    expireAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantsMerchantIdApplicationsPostRequest
     */
    isSandbox?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsPostRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the MerchantsMerchantIdApplicationsPostRequest interface.
 */
export function instanceOfMerchantsMerchantIdApplicationsPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MerchantsMerchantIdApplicationsPostRequestFromJSON(json: any): MerchantsMerchantIdApplicationsPostRequest {
    return MerchantsMerchantIdApplicationsPostRequestFromJSONTyped(json, false);
}

export function MerchantsMerchantIdApplicationsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantsMerchantIdApplicationsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expireAt': !exists(json, 'expire_at') ? undefined : json['expire_at'],
        'isSandbox': !exists(json, 'is_sandbox') ? undefined : json['is_sandbox'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function MerchantsMerchantIdApplicationsPostRequestToJSON(value?: MerchantsMerchantIdApplicationsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expire_at': value.expireAt,
        'is_sandbox': value.isSandbox,
        'name': value.name,
    };
}

