/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MerchantsMerchantIdApplicationsGet200ResponseDataInner
 */
export interface MerchantsMerchantIdApplicationsGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    isSandbox: boolean;
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantsMerchantIdApplicationsGet200ResponseDataInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MerchantsMerchantIdApplicationsGet200ResponseDataInner interface.
 */
export function instanceOfMerchantsMerchantIdApplicationsGet200ResponseDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isSandbox" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function MerchantsMerchantIdApplicationsGet200ResponseDataInnerFromJSON(json: any): MerchantsMerchantIdApplicationsGet200ResponseDataInner {
    return MerchantsMerchantIdApplicationsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function MerchantsMerchantIdApplicationsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantsMerchantIdApplicationsGet200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'id': json['id'],
        'isSandbox': json['is_sandbox'],
        'name': json['name'],
        'status': json['status'],
        'updatedAt': json['updated_at'],
    };
}

export function MerchantsMerchantIdApplicationsGet200ResponseDataInnerToJSON(value?: MerchantsMerchantIdApplicationsGet200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'id': value.id,
        'is_sandbox': value.isSandbox,
        'name': value.name,
        'status': value.status,
        'updated_at': value.updatedAt,
    };
}

