/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentsCardsUsersUserIdCardsPostRequest
 */
export interface PaymentsCardsUsersUserIdCardsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    address1?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    cardHolder?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    cardHolderDni?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    cardNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    expiryMonth?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    expiryYear?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsCardsUsersUserIdCardsPostRequest
     */
    zip?: string;
}

/**
 * Check if a given object implements the PaymentsCardsUsersUserIdCardsPostRequest interface.
 */
export function instanceOfPaymentsCardsUsersUserIdCardsPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentsCardsUsersUserIdCardsPostRequestFromJSON(json: any): PaymentsCardsUsersUserIdCardsPostRequest {
    return PaymentsCardsUsersUserIdCardsPostRequestFromJSONTyped(json, false);
}

export function PaymentsCardsUsersUserIdCardsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsCardsUsersUserIdCardsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address1': !exists(json, 'address1') ? undefined : json['address1'],
        'cardHolder': !exists(json, 'card_holder') ? undefined : json['card_holder'],
        'cardHolderDni': !exists(json, 'card_holder_dni') ? undefined : json['card_holder_dni'],
        'cardNumber': !exists(json, 'card_number') ? undefined : json['card_number'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'expiryMonth': !exists(json, 'expiry_month') ? undefined : json['expiry_month'],
        'expiryYear': !exists(json, 'expiry_year') ? undefined : json['expiry_year'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
    };
}

export function PaymentsCardsUsersUserIdCardsPostRequestToJSON(value?: PaymentsCardsUsersUserIdCardsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address1': value.address1,
        'card_holder': value.cardHolder,
        'card_holder_dni': value.cardHolderDni,
        'card_number': value.cardNumber,
        'city': value.city,
        'country': value.country,
        'expiry_month': value.expiryMonth,
        'expiry_year': value.expiryYear,
        'phone': value.phone,
        'state': value.state,
        'zip': value.zip,
    };
}

