/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersUserIdCardsGet200ResponseInnerData } from './UsersUserIdCardsGet200ResponseInnerData';
import {
    UsersUserIdCardsGet200ResponseInnerDataFromJSON,
    UsersUserIdCardsGet200ResponseInnerDataFromJSONTyped,
    UsersUserIdCardsGet200ResponseInnerDataToJSON,
} from './UsersUserIdCardsGet200ResponseInnerData';

/**
 * 
 * @export
 * @interface UsersUserIdCardsPost200Response
 */
export interface UsersUserIdCardsPost200Response {
    /**
     * 
     * @type {UsersUserIdCardsGet200ResponseInnerData}
     * @memberof UsersUserIdCardsPost200Response
     */
    data?: UsersUserIdCardsGet200ResponseInnerData;
}

/**
 * Check if a given object implements the UsersUserIdCardsPost200Response interface.
 */
export function instanceOfUsersUserIdCardsPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersUserIdCardsPost200ResponseFromJSON(json: any): UsersUserIdCardsPost200Response {
    return UsersUserIdCardsPost200ResponseFromJSONTyped(json, false);
}

export function UsersUserIdCardsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersUserIdCardsPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UsersUserIdCardsGet200ResponseInnerDataFromJSON(json['data']),
    };
}

export function UsersUserIdCardsPost200ResponseToJSON(value?: UsersUserIdCardsPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UsersUserIdCardsGet200ResponseInnerDataToJSON(value.data),
    };
}

