/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeGet200ResponseIdentityProvidersInner
 */
export interface UsersMeGet200ResponseIdentityProvidersInner {
    /**
     * 
     * @type {string}
     * @memberof UsersMeGet200ResponseIdentityProvidersInner
     */
    createdAt?: string;
    /**
     * 
     * @type {any}
     * @memberof UsersMeGet200ResponseIdentityProvidersInner
     */
    deletedAt?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UsersMeGet200ResponseIdentityProvidersInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersMeGet200ResponseIdentityProvidersInner
     */
    providerName?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMeGet200ResponseIdentityProvidersInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the UsersMeGet200ResponseIdentityProvidersInner interface.
 */
export function instanceOfUsersMeGet200ResponseIdentityProvidersInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersMeGet200ResponseIdentityProvidersInnerFromJSON(json: any): UsersMeGet200ResponseIdentityProvidersInner {
    return UsersMeGet200ResponseIdentityProvidersInnerFromJSONTyped(json, false);
}

export function UsersMeGet200ResponseIdentityProvidersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeGet200ResponseIdentityProvidersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'deletedAt': !exists(json, 'deleted_at') ? undefined : json['deleted_at'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'providerName': !exists(json, 'provider_name') ? undefined : json['provider_name'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function UsersMeGet200ResponseIdentityProvidersInnerToJSON(value?: UsersMeGet200ResponseIdentityProvidersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'deleted_at': value.deletedAt,
        'id': value.id,
        'provider_name': value.providerName,
        'updated_at': value.updatedAt,
    };
}

