/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersUserIdCardsGet200ResponseInnerDataTokensInner } from './UsersUserIdCardsGet200ResponseInnerDataTokensInner';
import {
    UsersUserIdCardsGet200ResponseInnerDataTokensInnerFromJSON,
    UsersUserIdCardsGet200ResponseInnerDataTokensInnerFromJSONTyped,
    UsersUserIdCardsGet200ResponseInnerDataTokensInnerToJSON,
} from './UsersUserIdCardsGet200ResponseInnerDataTokensInner';

/**
 * 
 * @export
 * @interface UsersUserIdCardsGet200ResponseInnerData
 */
export interface UsersUserIdCardsGet200ResponseInnerData {
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    cardHolder?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    cardHolderDni?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    deletedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    expirationDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    firstSix?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    lastFour?: string;
    /**
     * 
     * @type {Array<UsersUserIdCardsGet200ResponseInnerDataTokensInner>}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    tokens?: Array<UsersUserIdCardsGet200ResponseInnerDataTokensInner>;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersUserIdCardsGet200ResponseInnerData
     */
    userId?: string;
}

/**
 * Check if a given object implements the UsersUserIdCardsGet200ResponseInnerData interface.
 */
export function instanceOfUsersUserIdCardsGet200ResponseInnerData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersUserIdCardsGet200ResponseInnerDataFromJSON(json: any): UsersUserIdCardsGet200ResponseInnerData {
    return UsersUserIdCardsGet200ResponseInnerDataFromJSONTyped(json, false);
}

export function UsersUserIdCardsGet200ResponseInnerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersUserIdCardsGet200ResponseInnerData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardHolder': !exists(json, 'card_holder') ? undefined : json['card_holder'],
        'cardHolderDni': !exists(json, 'card_holder_dni') ? undefined : json['card_holder_dni'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'deletedAt': !exists(json, 'deleted_at') ? undefined : json['deleted_at'],
        'expirationDate': !exists(json, 'expiration_date') ? undefined : json['expiration_date'],
        'firstSix': !exists(json, 'first_six') ? undefined : json['first_six'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastFour': !exists(json, 'last_four') ? undefined : json['last_four'],
        'tokens': !exists(json, 'tokens') ? undefined : ((json['tokens'] as Array<any>).map(UsersUserIdCardsGet200ResponseInnerDataTokensInnerFromJSON)),
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function UsersUserIdCardsGet200ResponseInnerDataToJSON(value?: UsersUserIdCardsGet200ResponseInnerData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_holder': value.cardHolder,
        'card_holder_dni': value.cardHolderDni,
        'company': value.company,
        'created_at': value.createdAt,
        'deleted_at': value.deletedAt,
        'expiration_date': value.expirationDate,
        'first_six': value.firstSix,
        'id': value.id,
        'last_four': value.lastFour,
        'tokens': value.tokens === undefined ? undefined : ((value.tokens as Array<any>).map(UsersUserIdCardsGet200ResponseInnerDataTokensInnerToJSON)),
        'updated_at': value.updatedAt,
        'user_id': value.userId,
    };
}

