/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersRequestCodePostRequest
 */
export interface UsersRequestCodePostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersRequestCodePostRequest
     */
    email: string;
}

/**
 * Check if a given object implements the UsersRequestCodePostRequest interface.
 */
export function instanceOfUsersRequestCodePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UsersRequestCodePostRequestFromJSON(json: any): UsersRequestCodePostRequest {
    return UsersRequestCodePostRequestFromJSONTyped(json, false);
}

export function UsersRequestCodePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRequestCodePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UsersRequestCodePostRequestToJSON(value?: UsersRequestCodePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

