/* tslint:disable */
/* eslint-disable */
/**
 * API Gateway
 * API Gateway
 *
 * The version of the OpenAPI document: 1.0
 * Contact: checkout@deuna.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersMeGet401Response
 */
export interface UsersMeGet401Response {
    /**
     * 
     * @type {string}
     * @memberof UsersMeGet401Response
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMeGet401Response
     */
    message?: string;
}

/**
 * Check if a given object implements the UsersMeGet401Response interface.
 */
export function instanceOfUsersMeGet401Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersMeGet401ResponseFromJSON(json: any): UsersMeGet401Response {
    return UsersMeGet401ResponseFromJSONTyped(json, false);
}

export function UsersMeGet401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersMeGet401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function UsersMeGet401ResponseToJSON(value?: UsersMeGet401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
    };
}

