/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.apigw-kotlin-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param id 
 * @param providerName 
 * @param updatedAt 
 */


data class GetUserInformation200ResponseIdentityProvidersInner (

    @Json(name = "created_at")
    var createdAt: kotlin.String? = null,

    @Json(name = "deleted_at")
    var deletedAt: kotlin.Any? = null,

    @Json(name = "id")
    var id: java.math.BigDecimal? = null,

    @Json(name = "provider_name")
    var providerName: kotlin.String? = null,

    @Json(name = "updated_at")
    var updatedAt: kotlin.String? = null

)

