/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.deuna.apigw-kotlin-sdk.models

import io.deuna.apigw-kotlin-sdk.models.GetUserInformation200ResponseIdentityProvidersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param email 
 * @param firstName 
 * @param id 
 * @param identityProviders 
 * @param isGuest 
 * @param isPhoneVerified 
 * @param lastName 
 * @param merchantId 
 * @param phone 
 * @param updatedAt 
 */


data class GetUserInformation200Response (

    @Json(name = "created_at")
    var createdAt: kotlin.String? = null,

    @Json(name = "deleted_at")
    var deletedAt: kotlin.Any? = null,

    @Json(name = "email")
    var email: kotlin.String? = null,

    @Json(name = "first_name")
    var firstName: kotlin.String? = null,

    @Json(name = "id")
    var id: kotlin.String? = null,

    @Json(name = "identity_providers")
    var identityProviders: kotlin.collections.MutableSet<GetUserInformation200ResponseIdentityProvidersInner>? = null,

    @Json(name = "is_guest")
    var isGuest: kotlin.Boolean? = null,

    @Json(name = "is_phone_verified")
    var isPhoneVerified: kotlin.Boolean? = null,

    @Json(name = "last_name")
    var lastName: kotlin.String? = null,

    @Json(name = "merchant_id")
    var merchantId: kotlin.String? = null,

    @Json(name = "phone")
    var phone: kotlin.String? = null,

    @Json(name = "updated_at")
    var updatedAt: kotlin.String? = null

)

