name: Upload to Maven Central
on:
  workflow_dispatch:

permissions:
  contents: read    # This is required for actions/checkout

env:
  MAVEN_URL: ${{ secrets.MAVEN_URL }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        env:
          MAVEN_URL: ${{ env.MAVEN_URL }}
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
        run: ./gradlew clean assemble publish -PurlMaven="$MAVEN_URL" -PusernameMaven="$MAVEN_USERNAME" -PpasswordMaven="$MAVEN_PASSWORD"
