name: Upload to CodeArtifact

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install and configure AWS CLI
        run: |
          pip install awscli
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install and authenticate with CodeArtifact
        run: |
          aws codeartifact login --tool npm --repository ${{ secrets.ARTIFACT_REPOSITORY }} --domain ${{ secrets.ARTIFACT_DOMAIN }} --domain-owner ${{ secrets.DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}
      - name: Publish package to CodeArtifact
        run: |
          npm publish ./javascript --registry=https://${{ secrets.ARTIFACT_DOMAIN }}-${{ secrets.ARTIFACT_REPOSITORY }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/${{ secrets.ARTIFACT_REPOSITORY }}/ --access private