name: Upload to CodeArtifact

env:
  ROLE_TO_ASSUME : "arn:aws:iam::628469270878:role/RoleForGithubPushCodeArtifactAllService" ## Role to Assume WITH Policy
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install and configure AWS CLI
        run: |
          pip install awscli
      - name: Install dependencies
        run: |
          cd ./clients/javascript
          npm install @babel/plugin-syntax-dynamic-import
          npm install
      - name: Configure AWS and Publish package to CodeArtifact
        run: |
          aws configure set region ${{ secrets.AWS_REGION }}    
          aws codeartifact login --tool npm --repository ${{ secrets.ARTIFACT_REPOSITORY }} --domain ${{ secrets.ARTIFACT_DOMAIN }} --domain-owner ${{ secrets.DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}
          npm publish ./clients/javascript